### ISSUE TITLE
Create a new platform for shamela.ws

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#1023]
For https://github.com/openzim/zim-requests/issues/1172, we are going to have 40 recipes, one per category on shamela.ws to have pratical recipe duration and practical ZIM sizes.

However, there is only one upstream server, so we need to ensure that we do not run more than one task (out of these 40 recipes) per worker, or even probably only one task on the whole platform to be fair with their servers.

Shall we create a new `shamela.ws` platform we would assign manually to the corresponding recipes?

**Comment by rgaudin** [comment]
I am torn. On one hand, it has virtually no cost for us to do, so I'd be in favor but on the other, it's just 40 concurrent access crawling parts of the website (with little overlap) so just setting a reasonable delay should do it.
We can discuss it today.
I see there's a contact email and they've gone great lengths to make this available with android/ios/windows softwares so they seem keen on distributing it offline widely. We could simply ask.

**Comment by benoit74** [comment]
Discuss yesterday in team meeting, we agree that we need to create a new platform.
