### ISSUE TITLE
Cloning a recipe and provide a new name which already exists seems to fail

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#1036]
Steps:
* Cloning a recipe
* Entry a name which already exists, here `sorcier_fr_economie`
* I get no result (so no new recipe)... and it seems it modifies an old recipe

Not sure if this is reproducable

I didn't want to try again...

**Comment by benoit74** [comment]
It is failing with a 500 (this is tracked at https://github.com/openzim/zimfarm/issues/844)

It is not moving anywhere (just tested twice in a row right now):

![Image](https://github.com/user-attachments/assets/6eb2d1f4-9fae-4e54-81d9-e57048a34de9)

Closing this duplicate.

**Comment by benoit74** [comment]
Btw, alarming on these 500 errors was broken, it is now fixed.
