### ISSUE TITLE
HTTP 503: Recording IP changes failed

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#1049]
During first launch of `rhys` worke `zimfarm logs manager`:
```
[2024-11-16 16:24:07,193: INFO] testing workdir at /data…
[2024-11-16 16:24:07,193: INFO] 	workdir is available and writable
[2024-11-16 16:24:07,193: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2024-11-16 16:24:07,230: INFO] 	private key is available and readable (906f58474862b3e463bf920cc8494318)
[2024-11-16 16:24:07,230: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2024-11-16 16:24:07,535: INFO] 	authentication successful
[2024-11-16 16:24:07,535: INFO] testing docker API on /var/run/docker.sock…
[2024-11-16 16:24:07,548: INFO] 	docker API access successful
[2024-11-16 16:24:07,551: INFO] Host hardware resources:
	CPU : 3 (total) ;  3 (avail)
	RAM : 7 GiB (total) ;  7 GiB (avail)
	Disk: 800 GiB (configured) ; 866.19 GiB (avail) ; 0 bytes (reserved) ; 800 GiB (remain)
[2024-11-16 16:24:07,551: INFO] checking-in with the API at api.farm.openzim.org…
[2024-11-16 16:24:07,681: INFO] 	checked-in!
[2024-11-16 16:24:07,682: INFO] registering exit signals
[2024-11-16 16:24:07,703: DEBUG] polling api.farm.openzim.org…
[2024-11-16 16:24:07,854: WARNING] poll failed with HTTP 503: Recording IP changes failed
[2024-11-16 16:27:07,877: DEBUG] polling api.farm.openzim.org…
[2024-11-16 16:30:08,210: DEBUG] polling api.farm.openzim.org…
```

**Comment by rgaudin** [comment]
We have the IP in the DB but it's not in the Wasabi policy.

**Comment by benoit74** [comment]
Full error:

```
1731917874003	INFO:routes.requested_tasks.requested_task:Worker IP changed detected for rhys: IP changed from None to 185.xxx.xxx.xxx
1731917874017	ERROR:routes.requested_tasks.requested_task:Pushing IP changes to Wasabi failed
1731917874017	Traceback (most recent call last):
1731917874017	  File "/app/./routes/requested_tasks/requested_task.py", line 250, in get
1731917874017	    record_ip_change(session=session, worker_name=worker_name)
1731917874017	  File "/app/./routes/requested_tasks/requested_task.py", line 42, in record_ip_change
1731917874017	    update_workers_whitelist(session)
1731917874017	  File "/app/./common/external.py", line 32, in update_workers_whitelist
1731917874017	    ExternalIpUpdater.update(build_workers_whitelist(session=session))
1731917874017	  File "/app/./common/external.py", line 41, in build_workers_whitelist
1731917874017	    wl_networks.append(ipaddress.ip_network(item))
1731917874017	  File "/usr/local/lib/python3.8/ipaddress.py", line 79, in ip_network
1731917874017	    return IPv6Network(address, strict)
1731917874017	  File "/usr/local/lib/python3.8/ipaddress.py", line 2113, in __init__
1731917874017	    raise ValueError('%s has host bits set' % self)
1731917874017	ValueError: xxxx:xxx:xxxx:xxxx::2/64 has host bits set
1731917874018	[pid: 30|app: 0|req: 20/56] 100.xx.xx.xx () {52 vars in 1358 bytes} [Mon Nov 18 08:17:53 2024] GET /v1/requested-tasks/worker?worker=rhys&avail_cpu=0&avail_memory=3221225472&avail_disk=923230134272 => generated 48 bytes in 26 msecs (HTTP/1.1 503) 3 headers in 120 bytes (1 switches on core 0)
1731917874018	100.xx.xx.xx - - [18/Nov/2024:08:17:54 +0000] "GET /v1/requested-tasks/worker?worker=rhys&avail_cpu=0&avail_memory=3221225472&avail_disk=923230134272 HTTP/1.1" 503 48 "-" "python-requests/2.31.0" "185.xxx.xxx.xxx"
```

(I've redacted IPs)

`xxxx:xxx:xxxx:xxxx::2/64` is an IP from the `WHITELISTED_IPS` environment variable. There is no reason to have the `/64` in the whitelist, we want to whitelist only the host and not the whole range. I removed the `/64` and everything seems to be fine now.

I couldn't confirm the worker really has access to S3 since it is already full with a task which is going to take ages.

**Comment by rgaudin** [comment]
Ah OK. So this means we could not update the wasabi whitelist last month. I suppose since all workers are on fixed public IP that wasn't an issue.

> There is no reason to have the /64 in the whitelist, we want to whitelist only the host and not the whole range

That's misleading. We can want a range and we do for other workers. It's just that this particular one had the host bit set `:2` and the calculator is strict in requesting a network with the CIDR. You could have removed the trailing `2` and it would have worked (using the range and not the unique IP). 

Why do we have kstorage in this whitelist in the first place ?

> I couldn't confirm the worker really has access to S3 since it is already full with a task which is going to take ages.

You should look into wasabi's policy for that. I just did, IP's in there 👍

**Comment by benoit74** [comment]
> I suppose since all workers are on fixed public IP that wasn't an issue.

Yes

> That's misleading. We can want a range and we do for other workers. It's just that this particular one had the host bit set :2 and the calculator is strict in requesting a network with the CIDR. You could have removed the trailing 2 and it would have worked (using the range and not the unique IP).

OK

> Why do we have kstorage in this whitelist in the first place ?

I'm not 100% sure, but I think it is used for the SE watcher?

> You should look into wasabi's policy for that. I just did, IP's in there 👍

I did, but I prefer to run something than trusting that I've checked everything ^^ (sorry for not being specific enough in saying that I did check wasabi policy)

**Comment by rgaudin** [comment]
> I'm not 100% sure, but I think it is used for the SE watcher?

Ah that's it. thank you.
