### ISSUE TITLE
Machine readable format for all schedules

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#129]
This is important for transparency and backup.

**Comment by automactic** [comment]
Done. Not posting the API here since we don't want malicious users to DDOS the server

**Comment by kelson42** [comment]
@automactic Can you please send me an email to let me know how to do that? If you fear a DDOS, please protect it behind a password.

**Comment by automactic** [comment]
> how to do that
how to do what??

**Comment by kelson42** [comment]
@rgaudin I think we have one now... but this is not documented AFAIK

**Comment by rgaudin** [comment]
Yes, what's the name of that format/tool you mentioned the other day for API description?

**Comment by rgaudin** [comment]
Done, documenting API in #275
