### ISSUE TITLE
Wikipedia simple has a bad name

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#156]
for simple.wikipedia.org I get a ZIM file like `wikipedia_en_all_nopic_2019-03.zim`, but I should get a ZIM file like `wikipedia_en_simple_all_nopic_2019-03.zim`

This was handle as an exception in `mwmatrixoffliner`.

**Comment by automactic** [comment]
added `--filenamePrefix=wikipedia_en_simple` as a extra flag to the command. re-running now to make sure it works

**Comment by automactic** [comment]
Done the same for simple wiktionary, Wikibooks & Wikiquote.

**Comment by kelson42** [comment]
@automactic thx
