### ISSUE TITLE
Simple english wiktionary misnamed as "wiktionary_en_all_novid_2019-03.zim" without the "_simple"

### ISSUE THREAD

**Issue by pyroshroom** [openzim/zimfarm#159]
The newest simple english wiktionary zim (wiktionary_en_all_novid_2019-03.zim) lacks the "_simple" in the filename that previous simple english wiktionary zims had. It should be named "wiktionary_en_simple_all_novid_2019-03.zim" instead of "wiktionary_en_all_novid_2019-03.zim".

This is not an issue with the latest wikipedia_en_simple_all_novid_2019-03.zim which is named properly.

**Comment by automactic** [comment]
Closing this as this is tracked in #156.

**Comment by kelson42** [comment]
@automactic thx
