### ISSUE TITLE
Logs should be kept

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#174]
We need to keep the logs (stdout, stderr, etc.) for investigation reason, even if the scraping process has been (apparently) successful. We should do so, as long, as the scheduling has not run an other time. This logs should be easily available through API and Web UI, probably in a compressed formed.

**Comment by rgaudin** [comment]
Logs should be compressed and uploaded via SFTP to the warehouse as it will be kept only for debugging purposes and doesn't need to interact much with the zimfarm. A way to access/retrieve from the zimfarm should be enough.

## challenges (based on mwo):

* logs are expected to be GBs large (compressed). With about 1,500 schedules (most being smaller ZIMs), we are talking about hundreds of GBs of compressed logs at any given time.
* creation process takes days
* there is almost-constant output during that time
* writing those logs to disk **might** slow down the process? (ie. consume I/Os)
* keeping those logs to RAM might slow down the process (ie. consume precious RAM)
* periodic upload of chunks would solve those two but would mean uploading/appending uncompressed logs to the warehouse: too large to keep on the WH, too large to DL for users and a general waste of BW. Compressing it on the WH seems fragile and CPU-intensive (not the role of the WH).

## Option

Given the scrappers are running in docker, logs are already written to disk (on host at `/var/lib/docker/<cid>/<cid>-json.log`) so there's no additional impact on scrapper performance. It thus seems reasonable to just retrieve and compress the whole docker log.

`xz` compression seems appropriate as our workers are already doing CPU-intensive work and we'll want to save space on WH. `xz` also un-compresses very fast which will make it easy for users/debugging.

We'll want to store it at `/logs/<task_id>.log.xz` for easy retrieval. (ie. `/data/zimfarm-warehouse/logs` on the server).

We are currently sending the last 100 lines of `stdout` and the entirety of `stderr` via rabbitmq. It is expected we'll continue to send both this way and additionally compress/upload the full `stdout`. We might revise this should a scrapper write tons of stuff to `stderr` but it is unlikely and might make more sense to be fixed on the scrapper.

So, on task received, we'll:

* get last task ran for schedule
* remove `<previous_task_id>.log.xz` on warehouse
* [normal worker work]
* on task completion (whatever the reason):
  * get and compress the full log (not just the tail) ⌛️ 
  * upload the full log to WH ⌛️ 
  * still upload tail via rabbitmq

**Comment by kelson42** [comment]
@rgaudin has done this.
