### ISSUE TITLE
redis should not write to the fs

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#195]
This takes time and is not necessary. Here was the configuration before we start to use the Zimfarm.

```
save ""
appendfsync no
```

**Comment by automactic** [comment]
Could you please specify what exactly is the configuration needed for redis?

**Comment by kelson42** [comment]
@automactic This is exactly what I have given, not more not less. The rest is the default configuration.

**Comment by automactic** [comment]
Not super familiar with Redis, but can you pass those configs through the command line or an env? Or do you have to create a `redis.conf` and map it in the container?

**Comment by rgaudin** [comment]
Yes, I just confirmed it works as expected with

``` sh
docker run --volume /data/:/data:rw --name redis redis:latest redis-server --save "" --appendonly no
```

I will commit this to the run_redis part of the zimfarm today.

Not sure it will provide much perf gain though as redis seems quite optimized in doing saves in the background. But definitely something we need anyway.
