### ISSUE TITLE
Add more contextual and introductory descriptions

### ISSUE THREAD

**Issue by mhucka** [openzim/zimfarm#24]
I'm learning about ZIM and related efforts, and came across this repo, but am having trouble wrapping my head around what ZIM farm is about. I realize that my difficulty is entirely because I don't have sufficient background knowledge in this particular effort (or ZIM in general, for that matter); my point in bringing this up here is that I think I may not be alone, and adding some additional explanations may help other people in the future.

The front README has the following brief explanation:

_A farm operated by bots to grow and harvest new zim files. User can submit a new zim file generate task through the website and a registered worker will run the task and upload the file back to the dispatcher._

But to an outsider such as me, there is not enough context to understand this summary. For example, when it says "harvest new zim files", _where_ are those files being harvested from? When it says "upload the file back to the dispatcher", what _is_ the dispatcher? What is its role? (It's not even clear whether it's part of ZIM farm.) And finally, _why_ would one want to harvest ZIM files in the first place?

A section on background or a longer introduction might clear up these questions for me and others.

In any case, thank you for your efforts on ZIM and the associated infrastructure.

**Comment by kelson42** [comment]
Dear Mike, thank you for taking time to complain about this. Please have a look to the PR I just made, and let us know if your questions are answered.

**Comment by automactic** [comment]
@mhucka, please check our new readme! 

Thanks for your interest in the project. And suggestions are welcome, just create a new issue!

**Comment by mhucka** [comment]
@kelson42 My apologies if the tone of my issue/ticket made it seem like a complaint; I did not mean it that way, and meant it more like a constructive suggestion. 

@automactic and @kelson42: thank you both for the updated README! The new text is hugely helpful. I think I now fully understand zimfarm. (And it's a cool system, btw.)
