### ISSUE TITLE
Reduce the amount of info retrieved by list schedule API

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#242]
Currently the list schedules API returns the whole schedule object. Can we reduce the amount of info in the response json? I plan to use the following fields in the UI. And all other fields could / should be removed.

Field the UI is gonna use:
- _id
- name
- category
- language
- most_recent_task

You might notice that in the new UI, I am still displaying image tag and name. I am planning to replace this by the task run this month (most_recent_task). So please don't work on this ticket until after I made this change in UI.

**Comment by kelson42** [comment]
@automactic I'm not sure about the problem we want to resolve here? Do we have a performance problem? On the backend or UI? At the time we will create a command line client, I'm quite sure all the properties of the schedules will be needed.

**Comment by rgaudin** [comment]
In general, it's good REST practice to have few descriptive data in the items list and the full object on the dedicated endpoint so it's fine by me.

it's what most API users would expect.

**Comment by kelson42** [comment]
@rgaudin Do we have these two kinds of end points so far?

**Comment by rgaudin** [comment]
Yes, `/schedules/<id>` is the one returning the full document.

@automactic wants to simplify `/schedules/` list I think.

**Comment by kelson42** [comment]
@rgaudin @automactic good!

**Comment by automactic** [comment]
Yes, I want list schedule `GET api/schedules/` to return less stuff, so I can have larger page sizes.
