### ISSUE TITLE
Setup dispatcher container logs retention policy

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#247]
There was an incident that dispatcher's disk was full. I dug around and found that the logs for the generator container was 42GB. So I fixed it by deleting the container and restart it. 

We should have a logs retention policy for the generator container. 

ref: https://docs.docker.com/config/containers/logging/configure/

**Comment by kelson42** [comment]
@automactic @rgaudin I think this is still a good source of potential problem. IMO We should "just" run the Docker container with the two right Docker parameters `--max-size` and `--max-file` to avoid huge log files.

**Comment by rgaudin** [comment]
I agree. Currently, mongo container log is 27GB…

We should definitely set `max-size` and `max-file` in `daemon.log` for the servers we manage and run our containers with these options for those we don't.

This is of course not limited to the zimfarm and should probably feed-into kiwix-wide Good Practices for sysadmin stuff.

Also, except for the warehouses, this would be rendered irrelevant by #278.
