### ISSUE TITLE
Schedule details view should provide the scraper execution line

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#253]
This is really important to try to reproduce problem locally. Ultimately, an importer (from the command line) to a scheduler would be really helpful to import a new schedule from a manual test.

**Comment by rgaudin** [comment]
I think there are two very different requests here.

As for the first one, we have that output in the task detail (not schedule detail). I think it's the right place.

As for the importer, what's the use case exactly ? Can you give an example?

**Comment by kelson42** [comment]
@mgautierfr Forget about the importer, because indeed this is an other request. I will open a new ticket when I'm so far. I'm OK with the tasks... but the pb is that most of the schedules don't have corresponding tasks currently!

**Comment by rgaudin** [comment]
It's not really relevant to have the _command_ on the schedule as the command is generated by the container which will be instantiated only when the task is run.

I think this _issue_ should be solved by having access to previous tasks ran from the schedule detail page. It would be both convenient and accurate. Would that work?

**Comment by kelson42** [comment]
@rgaudin I remark that my ticket is really poorly written. Sorry about that. The first point can be verified with the command of the last executed task and the second point is an other feature request. My need is the following: I want easily to be able to check what a schedule does (or will do)... and the best way for that (at least for me as a developer) is to see the command line at this level.

The problem with the past/current tasks is that the tasks command is not the same as what I need. What happens for example if:
* the schedule configuration has changed in the meantime? Then the command visible in the task won't be the same as the current schedule one or future one!
* The schedule has no tasks scheduled?
* The schedule is configured with a new version of the scraper Docker image and the options have changed (in comparison to the already existing tasks).

Conceptually the command in the tasks is not the same as the command in the scheduler. It might be the same, but it does not have to be the same.

The command executed by scraper container has to be "computed" by the zimfarm code... or then there is something I really don't understand properly. It should be perfectly possible to know how will look like the command in the next to-be-created related schedule task.

**Comment by rgaudin** [comment]
Following discussion with @kelson42, it appears we'd like to move the command-generation code to the backend and submit that information to the worker.

Reasoning: we'd want the worker to be as dumb as possible so that its maintenance is the easiest.

this is particularly useful for welcoming third-party worker providers (which we won't be able to restart every now and then).

@automactic, we shall discuss this in a future meeting. Not urgent.
