### ISSUE TITLE
Schedule value are not refreshed properly if null/empty string

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#258]
Steps:
1 - Filter schedules with string "wikivoyage"
2 - Click on "wikivoyage_en"
3 - Check "Custom main page", it is "Wikivoyage:Offline_reader_Expedition/Home_page"
4 - Click on "wikivoyage_fi"

You get:
1 - Check "Custom main page", it is "Wikivoyage:Offline_reader_Expedition/Home_page"

You should get (just refresh the page):
1 - Check "Custom main page", it is empty

**Comment by rgaudin** [comment]
First report and reply: [#241](https://github.com/openzim/zimfarm/pull/241#pullrequestreview-250540775)

**Comment by automactic** [comment]
Already fixed, but not deployed. I just made a new deploy, please check that it is fixed.

**Comment by kelson42** [comment]
good, even if it looks less fancy than before. Thx.
