### ISSUE TITLE
Specification on what config fields should be displayed for mwoffliner

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#259]
Could you specify what fields should be displayed for a mwoffliner schedule? There are a lot of fields and probably not all should be displayed.

While you are at it, could you specify how those fields are supposed to be displayed, maybe a text input, yes/no, multi-choice, etc? (basically sensible ways to not make them just a text box)

Extra mile: can you also come up a way to group those fields in sections and can you give a name for each section? For example, configs control how you connect to mediawiki should be grouped together in a section called `connection` or something like that.

**Comment by kelson42** [comment]
I don't understand why we need more than just a string for a command line arguments?

**Comment by automactic** [comment]
Can we please start by specifying a list of fields that should be displayed for a mwoffliner schedule?

**Comment by kelson42** [comment]
@automactic We should first discuss the needs, and then how to satisfy them. Not the other way around.

**Comment by kelson42** [comment]
Another problem with the current stuff is "format":
* It's presented with a comma as separator, but the comma is already used as option separator in the format value. We get this kind of things https://farm.openzim.org/schedules/wikipedia_en_medicine which are useless
* No way to know also if with have something like `--format=` which is valid. That would not be displayed.

**Comment by rgaudin** [comment]
Well on that last comment, @automactic said it's temporary and wants indication on how to display it. It's a list of options in the JSON data and should probably be displayed as a proper list of formats.

As for the rest, I believe we want to display all fields. Maybe we want just a slice at first and a `show all` toggle to see the rest? I that case, I'd prioritize:

* `mwUrl`
* `articleList`
* `customZimFavicon`
* `customZimTitle`
* `customZimDescription`
* `customMainPage`
* `format`

**Comment by rgaudin** [comment]
OK, so here's a list based on the [validator](https://github.com/openzim/zimfarm/blob/master/dispatcher/backend/src/routes/schedules/validators.py#L15).

* `mwUrl`: URL
* `adminEmail`: Email
* `articleList`: URL
* `customZimFavicon`: URL
* `customZimTitle`: String
* `customZimDescription`: String
* `customZimTags`: List of strings
* `customMainPage`: String
* `filenamePrefix`: String
* `format` Multiple choice list from (`nodet`, `nopic`, `novid`, `nopdf`, `nodet,nopic`, `nopic,nopdf`, `novid,nopdf`)
* `keepEmptyParagraphs`: Boolean
* `mwWikiPath`: String
* `mwApiPath`: String
* `mwModulePath`: String
* `mwDomain`: String
* `mwUsername`: String
* `mwPassword`: String
* `minifyHtml`: Boolean
* `publisher`: String
* `requestTimeout`: Integer
* `useCache`: Bool
* `skipCacheCleaning`: Boolean
* `speed`: Float
* `verbose`: Boolean
* `withoutZimFullTextIndex`: Boolean
* `addNamespaces`: String
* `getCategories`: Boolean
* `noLocalParserFallback`: Boolean

Most important ones are listed in previous comment.

As for display:
* _String_: regular input field
* _Integer_: input field with integer validation
* _Float_: input field with float validation
* _URL_: input field with URL validation
* _Email_: input field with email validation
* _List of strings (zim tags)_: could be a comma-separated input field.
* _Multiple choice list_: checkboxes or select-multiple field
* _Boolean_: checkbox or yes/no select field or switch field.
