### ISSUE TITLE
Suggest adding a contributions file

### ISSUE THREAD

**Issue by mhucka** [openzim/zimfarm#26]
A minor suggestion – not urgent and not a complaint – but future contributors may benefit from the addition of a CONTRIBUTING.md file at the top level of the repo. The file could describe the process(es) for how people can contribute to the project. (Examples of contributors' guidelines are plentiful on GitHub; I'm familiar with [EDGI](https://github.com/edgi-govdata-archiving/overview/blob/master/CONTRIBUTING.md)'s but there are other examples.)

**Comment by automactic** [comment]
Thanks for the suggestions, @mhucka! Yes, I think I will add such a file a bit later. Maybe once we deploy the first working version.

**Comment by kelson42** [comment]
@mhucka @automactic I have copied the one of the openZIM project to the zimfarm repository.
