### ISSUE TITLE
Add loading feedback

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#270]
At the moment, there is no visual feedback of content loading. On a slow connection, it is very difficult to acknowledge that an UI action (click, filter, etc) has been recorded.

I believe a subtle feedback would really improve user experience.

**Comment by kelson42** [comment]
@rgaudin A spider? Something blocking the page as long as the loading is not over?

**Comment by rgaudin** [comment]
I think there are many options (loading bar, greying out, spining stuff, etc) and I'm sture @automactic has ideas.

If you want to try some of the frustration, use the GRPS mode in the _throttling_ selector under the _Responsive Design Mode_ of your browser's tools.

**Comment by kelson42** [comment]
HTTP compression should be checked here.

**Comment by rgaudin** [comment]
OK it wasn't enabled. I've enabled and tested it. It's working. While it was definitely needed, I still suggest we get a loading feedback.

@automactic are the files in `/data/nginx` (templates mostly) versioned?

**Comment by kelson42** [comment]
@rgaudin Great, would recommend to open separate ticket+PR just for that.

**Comment by rgaudin** [comment]
why separate ? it’s the actual topic. your question diverged (gzip) but is
fixed already.

**Comment by kelson42** [comment]
@rgaudin Because the HTTP compression is a side topic, but if you have fixed it already (I have missed the PR) then there is nothing more to do (regarding HTTP compression).

**Comment by rgaudin** [comment]
no PR, it was completely server side, hence my question about nginx conf
being versioned or not.

**Comment by kelson42** [comment]
@rgaudin I have the feeling here that a proper API with a care about which data are returned to the frontend should be enough (no need to implement a spider). What do you think?
