### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#277]
Given the very asynchronous nature of the zimfarm (defined once, ran at an unknown moment in the next month), users might be interested in being notified of events happening in the zimfarm.

Let's assume people are only interested in **three events**: `started` and `succeeded` or `failed` which are both mutually exclusive.

General notifications (firing those notifications for all schedules) to a different space seems irrelevant as given the 1,000+ schedules we have it won't be anymore useful than an archive to browse. In this case, the WebUI is sufficient.

What would be relevant though is for people to _register_ to some schedules. The use case I have in mind is one user adding a new schedule and wanting to be notified of the next run to check whether it's successful. A derivative is following a previously erroneous run.

**note**: this is for zimfarm users, not ZIM users. If there's a need for Kiwix users to be informed of new ZIM file releases, it's different.

Given the **very low expected number of users**, I suggest we start this with **email** notifications via [mailgun](https://www.mailgun.com/) (HTTP API) and see how it goes.

I suggest we store those _registrations_ on the `User` object in mongo as a `notifications` property:

``` json
"notifications": {
    "wikipedia_fr_test": ["started", "succeeded", "failed", "revoked"],
    "wikipedia_bm": ["succeeded"],
    "wikipedia_en_movies": ["started", "failed"]
}
```

This will require additional endpoints in the API to manage and an `email` property on the `User` as well.

@automactic, @kelson42, @Popolechien what do you think?

**Comment by Popolechien** [comment]
I for one am willing to challenge the idea that a sizeable part of our user base (zimfarm and zim users alike) would interested in anything else than ``successfuly updated``, as both ``started`` and ``failed`` bring nothing actionable (and even might be considered as somewhat frustrating). I mean, to some extent I could understand that ``failed`` calls for some maintenance response from zimfarm users, yes, but what is the informative value of ``started``? So that we know when a process takes longer than it should?
(I'm by far the less competent here, so I'm mostly asking for my own enlightenment)

This being said, it would be nice in the medium term to have the `succeed`` status being fed to at least our Twitter feed (e.g. "English Wikipedia (no images) zim has been updated [link]".

**Comment by rgaudin** [comment]
yeah, as I wrote earlier, this issue is only for zimfarm users (you, me, @kelson42 and @automactic at the moment).

I also think Kiwix should do a better job at informing people about new ZIM updates but this is completely different. It could be triggered by a webhook from the zimfarm to another tool or just by the file system on the download server. Anyway we'd probably don't want it automatic on every schedules as there are a thousand+ and many takes a few minutes (ie. flood).

I think yourself might be interested in notifications to communicate with other humans waiting for a new ZIM or a long awaited update. As for `started`, there's no way to know when a task will be ran (and so when it will be completed) so a `started` event is interesting ; especially for days/weeks-long ZIM creations.

My example shows that it would be per-user and per-schedule customizable (the events you want). As recently reminded by @kelson42, the zimfarm is mostly _a tool_ to ease _our_ life.

**Comment by kelson42** [comment]
@rgaudin I agree with you that Kiwix should do a better job to allow people to be informed about new job. Considering that the OPDS feed is based on Atom news feed, it could be used as an information feed. That said I was still not able to make all the filter like I wanted. This also does not mean that this should be the only one solution. I think here, what I would like to have is a third party notification system (supporting email, chat, etc...) we could use on demand.

**Comment by kelson42** [comment]
Here is a list of push notification solutions https://www.codeur.com/blog/outils-notifications-push-web/

**Comment by kelson42** [comment]
https://onesignal.com seems to be able to do the job for free (in our case).
