### ISSUE TITLE
Files should be uploaded as there are created

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#286]
At the moment, the scraper container runs and only once terminated, we upload all files in the mounted folder.

This behavior is fine for single-zim scraper but for those creating numerous files and/or very long ones, it would be much better to have ZIMs uploaded upon creation.

Examples:
* phet creating one ZIM per language
* gutenberg creating one ZIM per language and the whole task lasting about **a month**.
* large mwoffliner ones creating different flavours (`fr`, `en`, etc).

**Comment by kelson42** [comment]
@rgaudin Do you think this is fixed?

**Comment by rgaudin** [comment]
No.
