### ISSUE TITLE
Introduce StackExchange scraping / Sotoki

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#292]
One site per task

**Comment by saswat01** [comment]
one site per task refers to site of a single error right ?

**Comment by kelson42** [comment]
One zimfarm schedule/task per SE site

**Comment by kelson42** [comment]
We are mwanwhile in touch withSE people, we need that.

**Comment by rgaudin** [comment]
SE support is done. We've had a successful run on [conlang](https://farm.openzim.org/pipeline/5e07b2accb63c65a46f84de9) using 1GB RAM and 1GB disk (ZIM is 13.5M).

Could you please advise on how to extrapolate both RAM and disk from the existing list of ZIM so I can create the other schedules?

Also, I've used `--threads 8` for this run ; tell me what value to use for that as well.

**Comment by kelson42** [comment]
@dattaz Questions in last comment might be for you.

**Comment by dattaz** [comment]
`--threads` is the number of python Process (https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process) use to parallelize the work (except the downloading of the dump and its preparation)

**Comment by rgaudin** [comment]
what is the work that’s being parralelized ? what’s it doing ? On the
zimfarm we can’t rely on host’s advertised number of cores so we need to
set this value

**Comment by dattaz** [comment]
Generation of HTML and downloads/optimizes images. Each process do this for a set of questions/users.

**Comment by rgaudin** [comment]
OK thanks. So there's not much RAM being used, right?
