### ISSUE TITLE
(Docker) services should not use default port(s)

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#3]
At least for Redis, otherwise docker-compose might fail to start the containers because of conflicting ports with hosting system (in case this hosting system runs redis for example).

https://www.speedguide.net/port.php can be used to identify high-ranged ports which are not associated to any application.

**Comment by automactic** [comment]
No need to expose ports of rabbit and redis, since docker compose take care of communication between containers. 4aa689bf3b5111d2dc4feaa0fe5d85fe913e0e16
