### ISSUE TITLE
Provide standard way to report about scraping progress

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#331]
We need a standard way for the scraper itself to report its progress (0 -> 100%) through the Zimfarm to the end-user. This is needed to provide a user friendly scraping experience, in particular for future Zimit. This imply:
* Define a communication standard between the scraper and Zimfarm (see https://github.com/openzim/mwoffliner/issues/539)
* Implement it at Zimfarm level (and in the scrapers... but this is not the purpose if this ticket)
* Implement Zimfarm API to allow retrieval.

**Comment by kelson42** [comment]
The key problem here is the communication channel between the Zimfarm and the worker IMO. I think dealing with files is the most robust manner here. That means that the scraper should write a `status` file with a per-defined format understandable by the Zimfarm (worker?). This file would be then monitored and we should then decide how to transfer this information to the scheduler.

**Comment by kelson42** [comment]
@rgaudin Should we close this ticket?

**Comment by rgaudin** [comment]
done
