### ISSUE TITLE
Integrate ZIM Quarantine to the Zimfarm

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#333]
The ZIM Quarantine is a step which runs after a ZIM file is uploaded to the Warehouse and before the file is finally made available on download.kiwix.org. Its role is to check the quality of the produced ZIM file. It's vetting is based on `zimcheck` and beside publishing the content it cas also provide `zimcheck` logs and withdraw the publication. 

The code is here:
https://github.com/kiwix/maintenance/tree/master/zimquarantine-docker

The Goal is to fully integrate it to the Zimfarm as a new step to allow to better control the publication process.

**Comment by rgaudin** [comment]
done
