### ISSUE TITLE
Measure audience

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#344]
Audience of this web service should be measured. This is not only for the openZIM core team but also for a broader audience of people interested in ZIMified content. To achieve that this is easy:
* Create a new web site on stats.kiwix.org (admin)
* Put the piece of js code in each page here.

**Comment by kelson42** [comment]
@rgaudin I have created the config on stats.kiwix.org, you need to insert the piece of javascript given here https://stats.kiwix.org/index.php?module=CoreHome&action=index&showaddsite=1&period=day&date=yesterday&idSite=8&updated=1#?idSite=8&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

**Comment by rgaudin** [comment]
Done. will be visible on next deployment.
