### ISSUE TITLE
Selectbox for recipes Docker image tag

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#358]
It is currently a free text imput. It should propose/allow only the tags available on Docker Hub. This should be doable through a simple API call.

**Comment by rgaudin** [comment]
It's on purpose so we can set it to whatever we want, just as for the image.

What would be the added value of restricting it? Users would only change that knowing what they're doing or cloning from an existing working recipe.

**Comment by kelson42** [comment]
> What would be the added value of restricting it? Users would only change that knowing what they're doing or cloning from an existing working recipe.

Avoiding to make typos in tags. Such a solution for the image does not sound a bad idea either (does Sloppy works that way already?)

**Comment by kelson42** [comment]
Here is a typical API call:
https://hub.docker.com/v2/repositories/openzim/mwoffliner/tags/?page=1&page_size=250

Could we create a vue.js selectbox component which would print the current value, and if we click on it, dynamically populate the list based on this kind of call?

**Comment by kelson42** [comment]
@mahakporwal02 This might be an other potential task interesting for you.
