### ISSUE TITLE
SSH key upload via UI

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#363]
to simplify the process (API only at the moment)

**Comment by kelson42** [comment]
I strongly support that if we want to get more workers

**Comment by kelson42** [comment]
Conisering that we have already the API, might be something of interest to implement for you @mahakporwal02. @rgaudin Please let us know if you think differently.

**Comment by rgaudin** [comment]
Sounds good. @mahakporwal02, that would be [this part](https://github.com/openzim/zimfarm/tree/master/workers#uploading-your-public-key) except for the generation step of course.
You'd still need to read the file offline to extract the important part, format that as JSON and upload.

**Comment by rgaudin** [comment]
Following your question on slack, I think we can have this in the Users UI (on a user's profile detail) for now as this will mostly be used by admins, creating accounts for workers.
At some point, we'll probably gather access user-related stuff (token, password, etc) in some sort of profile but that's for later.
