### ISSUE TITLE
submit resources usage at end of scraper

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#377]
we want to know what were the resources usage (aka `docker stats`) of the scraper just before it failed.

This would help estimate if a failure is due to a lack of resources or not.

If we want this to be useful on successful runs as well, we might want to also/just record the maximum usage instead of the last one (not sure how/when scraper will free resources).

The maximum tells us how much it used when working (success) or how much it reached before failing.

We'd probably have to poll stats from the worker periodically and record/update the max to send on `scraper_completed`.

**Comment by kelson42** [comment]
@rgaudin AFAIK this has been implemented?! (But I can not find the corresponding PR)

**Comment by rgaudin** [comment]
That's right.
