### ISSUE TITLE
stupidedia does not display at all

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#393]
See at this URL https://farm.openzim.org/recipes/stupidedia
![image](https://user-images.githubusercontent.com/1029718/72684322-ec03a000-3adf-11ea-8980-b4c059c3999b.png)

**Comment by kelson42** [comment]
@rgaudin Quite a serious problem to me

**Comment by rgaudin** [comment]
It's displaying fine for me now. Can you please explain the steps you took to get to that empty recipe?
It's supposed to be like this in case of error in retrieving data albeit… it should display the error. Looks like we're not recording the error properly there.

**Comment by kelson42** [comment]
@rgaudin Works for me now. I was not doing anything special...
