### ISSUE TITLE
warn, if the filesystem uses Copy-on-write (default for btrfs)

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#402]
I haven't used zimfarm yet and don't know how the software works, but maybe it could make sense:

Ask the user if he really wants to run the worker on a [Copy-on-write](https://en.wikipedia.org/wiki/Copy-on-write) filesystem. I guess this is valid for all filesystems using cow. Since it can be switched off in btrfs by a mount option or by chattr +C \<filename\> there could also be an offer to change it or a suggestion how to switch it of for the worker directory.

As [documented in the btrfs wiki](https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Copy_on_Write_.28CoW.29)

>  The CoW operation is used on all writes to the filesystem (unless turned off, see below). 
>  This leads to fragmentation in heavily updated-in-place files like VM images and database stores.

**Comment by rgaudin** [comment]
I'm not sure I understand the pros and cons of it in the zimfarm situation.

Zimfarm itself is not responsible for much files operations obviously (docker container logs maybe?) but the scraper-workers it launches are.

Yet, those scrapers don't do frequent updates on the same files. Usual process is:

1. file is downloaded
2. [sometimes] file is re-compressed
3. file content is copied into ZIM file
5. file is deleted

Would this lead to more fragmentation on a CoW fs than on any other?

@JensKorte, please tell us more regarding the consequences of the described behavior so we can better understand if a warning is wanted and if so, what would be its message.

**Comment by JensKorte** [comment]
I close this issue since I guess I am wrong. Docker seems to utilize the features of btrfs. See <https://serverfault.com/questions/987018/should-i-disable-btrfs-cow-for-var-lib-docker> and <https://docs.docker.com/storage/storagedriver/btrfs-driver/>. With qemu and its images I am not sure. 

> I'm not sure I understand the pros and cons of it in the zimfarm situation.

Me too. ;)

In general to CoW: A small write IO leads to "read block (4kB?), modify in ram (some bytes), write block (4kB?) at a different position". Therefore a multiple of the few bytes are written for every small write.

Serial IO with CoW isn't much affected. The [default commit time for btrfs is 30 seconds](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs%285%29#MOUNT_OPTIONS) (scroll down to commit). Imho that means after 30 seconds data waiting in ram (dirty cache) is forced to be written, except when you force a file sync earlier. If you append to a zim file there should be no problems.
