### ISSUE TITLE
Alt tag for priority icon on farm.openzim.org

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#403]
[//]: # (Pick appropriate classifiers)
- Location: Website

## Problem

The icon for priority wasn't recognizable to me as priority. Maybe there could be an alt tag in the html code for it, like "priority".

[//]: # (Describe your issue)

## Reproducing steps
https://farm.openzim.org/recipes/teded_en_all in the line starting with "requested" near the end of the line

**Comment by mahakporwal02** [comment]
@rgaudin Can I work on this issue?

**Comment by rgaudin** [comment]
Sure, if @kelson42 can confirm this is an issue

**Comment by mahakporwal02** [comment]
@kelson42 Pls confirm it

**Comment by kelson42** [comment]
Yes, I propose `alt="Request with normal priority"` for the blue "Request" button and `alt="Request with high priority"` for the yellow one.
