### ISSUE TITLE
Aliases in zimfarm cmd line

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#417]
It would be nice to have aliases like zimfarm logs zimscraper/mwoffliner like zimfarm logs manager. If there are only 3 tasks running this is easy to define. If there are 6 or more running, I don't know which would be the best solution, using the first?
The same for: dnscache and zimtask

**Comment by rgaudin** [comment]
I think that if #418 is implemented properly, we shouldn't need this which would be better as this behavior, as you noted as flaws right from design :D What do you think? Should we drop this and focus on shell completion?

**Comment by JensKorte** [comment]
If bash completion is the better solution, I don't mind if this is dropped.
