### ISSUE TITLE
feature request: zimfarm.o.o: make workers table sortable

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#420]
It would be nice if the tables at <https://farm.openzim.org/workers> could be sorted ascending/descending by clicking on the header. The worker names have no header, maybe this could be added.

**Comment by mahakporwal02** [comment]
![Screenshot from 2020-12-11 23-28-13](https://user-images.githubusercontent.com/56486682/101937941-93ae2300-3c08-11eb-98c1-469849bbcd25.png)
@rgaudin @JensKorte

**Comment by kelson42** [comment]
@mahakporwal02 I would recommend to use a library which does that out of th box to avoid reinventing the wheel. Something like https://mottie.github.io/tablesorter/docs/

**Comment by kelson42** [comment]
After discussion with @mahakporwal02 and @rgaudin it seem quite difficult to implement this properly and the added value is really limited (for the moment. Closing the issue as WONTFIX.
