### ISSUE TITLE
Lots of errors “Unable to prune container”

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#421]
see https://farm.openzim.org/pipeline/5e50cfe60f16c4aab0527667/debug but this is common

**Comment by rgaudin** [comment]
Yes it’s a log but has no incidence

**Comment by kelson42** [comment]
Any chance to get ride of it? So many errors... which are not Real errors. This is a bit misleading.

**Comment by rgaudin** [comment]
Now obsolete
