### ISSUE TITLE
Limit docker commands (ps, prune, etc) to zimfarm-created docker resources

### ISSUE THREAD

**Issue by pirate** [openzim/zimfarm#423]
[//]: # (Pick appropriate classifiers)
- Location: Worker
- Schedule Name/ID: __n/a__
- Task ID: __n/a__

## Problem

Currently the `zimfarm.sh prune` command prunes the entire docker system, which can be dangerous when run on a host shared with other docker containers that the user may not want pruned. It's especially common for beginner docker users to forget to bind a folder or named volumes to their containers, so they end up with ephemeral volumes containing important application state that are just floating around, potentially no longer attached to their original containers. If the container happens to be stopped when they run `zimfarm prune` they will lose all those ephemeral volumes containing potentially important data.

**`zimfarm.sh:118`:**
```bash
# cleanup disk usage (to be run in cron)
function prune() {
    run docker system prune --volumes -af
}
```

It's especially important to restrict this when `--volumes --all and --force` are passed, as it won't even warn the user that they're deleting **all** unattached docker resources, not just zimfarm-related ones.

## Steps to reproduce

1. The user runs some stateful app without binding any volumes `docker run nextcloud:16`
2. User ends up with an unnamed volume containing all their important app state `docker volume ls` -> `49a9e29...`
3. User tries to upgrade their app version manually by stoping the container & deleting the old image, and starting the new image attached to the old volume
4. User's cronjob `zimfarm prune` happens runs in the background while they are doing this upgrade, and the unattached stateful volume from their app is instantly deleted because it's considered "unused" by docker (i.e. not attached to any running containers)

## Proposed fix

1. Add the label `zimfarm` label to all docker resources created by zimfarm

https://docs.docker.com/engine/reference/commandline/run/#set-metadata-on-container--l---label---label-file

```diff
# start or restart the manager using config values
function restart() {
    ...
    run docker run \
        --name $WORKER_MANAGER_NAME \
+       --label zimfarm \
        --restart=always \
    ...
}
```

2. Filter on that label when listing or pruning zimfarm related resources

https://docs.docker.com/engine/reference/commandline/ps/#options
https://docs.docker.com/engine/reference/commandline/system_prune/#options
https://docs.docker.com/engine/reference/commandline/system_prune/#filtering

```diff
# display a list of running containers with some zimfarm labels
function ps() {
-    run docker ps --format 'table {{.ID}}\t{{.Label "tid"}}\t{{.Label "schedule_name"}}\t{{.Label "task_id"}}\t{{.RunningFor}}\t{{.Names}}'
+    run docker ps --filter label=zimfarm --format 'table {{.ID}}\t{{.Label "tid"}}\t{{.Label "schedule_name"}}\t{{.Label "task_id"}}\t{{.RunningFor}}\t{{.Names}}'
}
```

```diff
# cleanup disk usage (to be run in cron)
function prune() {
-    run docker system prune --volumes -af
+    run docker system prune --volumes --all --force --filter=zimfarm
}
```

---

Let me know if this is an acceptable fix and I'll create a PR with the proposed patch ^.

**Comment by rgaudin** [comment]
Thanks @pirate, we knew it would be problematic someday but it slipped given we manage almost all workers so far :)

Thanks for the fix suggestion, it's actually not enough as the script just starts the _manager_ container, which is named and refreshed on each restart so your proposal would just prune this one (given it's not running).

We'd mostly want to get rid of the other containers (the task ones started by the manager and the ones that the task ones start themselves).

I'll make sure all containers are started with a `zimfarm` label and implement your prune fix.
