### ISSUE TITLE
In “Edit” flag, command flags should be hidden if...

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#427]
... there is no command flags like in gutenberg_mul_all.

**Comment by rgaudin** [comment]
You mean this part? What would you expect? No section? A sentence saying there's no configurable flags? 
![Zimfarm](https://user-images.githubusercontent.com/57929/75859750-81d65e80-5df2-11ea-9621-697e76843fa6.png)

**Comment by kelson42** [comment]
@rgaudin Yes, or print "No command flags".

**Comment by mahakporwal02** [comment]
@rgaudin @kelson42 Can I work on this issue?

**Comment by rgaudin** [comment]
Sure

**Comment by mahakporwal02** [comment]
@rgaudin pls review it
