### ISSUE TITLE
feature request: use PNGs from old ZIM file if possible

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#434]
When a ZIM file with PNGs is composed, it could be nice, if PNGs that are unchanged would be used from the old ZIM file.

how it could be:
1. recipe, a file with hashes (or PNG date/size) from the original pics and the old zim file with pics are downloaded
2. a container with the kiwix-serve is started and provides access to the old PNGs
3. when a PNG is needed either the file date and size (using http/html metadata w/o downloading the whole file) are used and compared to the list with old data or the PNG is downloaded and the checksum is compared to the old version. If it is a hit, the PNG is downloaded from the local webserver. If the download from local webserver fails or the date/size or hash doesn't fit, the new PIC is created like it is normally done.
4. the new list with date/size or hashes is uploaded with the ZIM file

I guess, the checksum way wouldn't provide much advantages. If the date and size data is provided by the server, then this way could save CPU cycles. I don't know how big the sum of the original image sizes is compared to the ZIM file with PNGs.

**Comment by kelson42** [comment]
We are currently implementing this using an online cache based on S3. We have started a rollout for MWoffliner and will move on our other scrapers in the next months hopefully.
