### ISSUE TITLE
make sure canceled tasks' data is removed

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#435]
It seems that under certain circumstances, `failed`, `canceled` or abandoned (`scraper_started`) tasks leave their data folder behind.

It's normal when upload failed for some reason, but it should for canceled or gone task.

list of folders left behind mwoffliner2. Needs status and ZIM upload status check for all to find out reasons:

```
Jan  6 11:15 5dff7d334c59425dce649257
Dec 24 09:24 5e00cd6428ab7f591f66be91
Jan  6 11:14 5e09058105d81a3840f85a2f
Jan  6 10:58 5e0f28d6f7d9bf7094d69fdf
Jan  4 08:52 5e105170938909d5d42bdf3d
Jan  6 10:42 5e105174938909d5d42bdf69
Jan  4 12:28 5e1051a3938909d5d42be19d
Jan  6 10:54 5e1051a3938909d5d42be1a5
Jan  6 10:54 5e1051a4938909d5d42be1a9
Jan  6 11:14 5e1051a4938909d5d42be1ad
Jan  6 10:58 5e1051a4938909d5d42be1b5
Jan  6 11:03 5e1051a5938909d5d42be1bd
Jan  6 10:46 5e1051a6938909d5d42be1cd
Jan  6 10:44 5e10d38f4e322a4ad62c0229
Jan  6 11:15 5e11e3bdbefd34b6532c3cee
Jan 22 15:59 5e12dc96751ea5b4642c877f
Jan  6 10:43 5e12dca8751ea5b4642c878c
Jan  6 10:46 5e12de851d00bc87df2d2285
Jan 22 16:01 5e1dd789637255cf61da6372
Jan 22 15:59 5e1dd7b7637255cf61da6531
Jan 22 16:07 5e1dd7dc637255cf61da66b1
Jan 22 16:12 5e1dd7f4637255cf61da67a7
Jan 22 16:07 5e1dd7f8637255cf61da67d3
Jan 22 16:05 5e1dd7fd637255cf61da6807
Jan 22 16:01 5e1dd7ff637255cf61da6819
Jan 22 16:06 5e1dd805637255cf61da6855
Jan 22 16:03 5e1dd809637255cf61da6885
Jan 22 16:03 5e1dd80e637255cf61da68bf
Jan 22 16:00 5e1dd80f637255cf61da68c7
Jan 22 16:03 5e1dd813637255cf61da68f1
Jan 22 16:10 5e1dd82f637255cf61da6a19
Jan 22 16:07 5e1dd893637255cf61da6e2b
Jan 23 01:57 5e1dd8a4637255cf61da6eb3
Jan 26 14:18 5e1dd8cd637255cf61da702b
Jan 20 12:19 5e252ca3fac4291f8f6524e2
Feb  5 00:58 5e3584bb18b1a86b5195baac
Feb 25 20:07 5e5196e8f7fed6918584d616
Mar  4 13:23 5e5971f21251926b93f37f2b
```

**Comment by HAKSOAT** [comment]
@rgaudin I'm trying to work on this.

I came across this part of the code base:

https://github.com/openzim/zimfarm/blob/504ac44fcd34d5fa188545f99a48c7cb48c83845/dispatcher/backend/src/common/utils.py#L18

Do you think this is where a modification will be needed? If yes, I'm not very clear on where the "data folder" comes in.

**Comment by rgaudin** [comment]
No it's definitely not there as this is backend code while the problem is on the worker side.

**Comment by HAKSOAT** [comment]
Okay. I'll take a look.

**Comment by HAKSOAT** [comment]
@rgaudin I noticed that we do not call the `clean_workdir` when an upload fails as seen here:

https://github.com/openzim/zimfarm/blob/504ac44fcd34d5fa188545f99a48c7cb48c83845/workers/app/task/worker.py#L335-L338

Is this one of such cases where data is left behind?

**Comment by rgaudin** [comment]
No it's not. When we fail to upload a ZIM, we don't want to erase it so we get to upload it manually later and clean manually.

The purpose of this issue is to research what happened in the mentioned tasks to find the reason(s) why we got left over files.

It's clearly not an easy task and would require good knowledge of the zimfarm behavior. That's why I assigned myself even though I couldn't find enough time to work on it yet.

**Comment by rgaudin** [comment]
All of those tasks that haven't been removed had a ZIM in it so there is no unexpected behavior: we keep the folder when we have a ZIM.

What we could do though is remove the folder if the task has been canceled as this imply it's not expected to produce a ZIM.
Now that we have working zimfarm and scrapers, I'd lean toward only keeping the folder if we do have ZIM files **and** the scraper exited with `0`. This way we'd only keep it on upload failures.

**Comment by kelson42** [comment]
We shoudl remove everything. I’m not interested anymore in the ability to upload manually ZIM. I trust and expect the Zimfarm to alwas upload properly. If not, the bug should be fixed and the recipe run a new time.
