### ISSUE TITLE
feature request: make numbers at api.farm.openzim.org/ better readable 

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#438]
The numbers at https://api.farm.openzim.org/v1/schedules/astronomy.stackexchange.com_en are very long. It would be nice if they are human readable (1M, 2G) or if the numbers had points like 1. 073.741.824 .

**Comment by rgaudin** [comment]
This is a JSON endpoint containing data.

If information that you consider usefull is not on [the UI](https://farm.openzim.org/) then open a ticket for that but the JSON endpoint is for machine-readable data.

**Comment by rgaudin** [comment]
Which ones were you talking about btw? Resources ? Durations ?

**Comment by JensKorte** [comment]
> Which ones were you talking about btw? Resources ? Durations ?

Ressources. It is at https://farm.openzim.org/recipes/astronomy.stackexchange.com_en/config
