### ISSUE TITLE
Add queue support

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#44]
Different kind of zim file generation requires different processing power. For large zim files, it might be better to generate them using a more powerful machine. It would be a good idea to add support for queues. 

When scheduling a task, user can choose which queue the task go to. Based on the file size, we might have the following queues: huge, large, medium, small, tiny, corresponding to 1000000+, 100000+, 10000+, 1000+, 100+ articles in the zimfile. 

When a worker starts, user can choose to join one or more queue.

**Comment by automactic** [comment]
@kelson42 What do you think are some appropriate levels of the queue? How about:

| Queue  | Expected File Size |
|--------|--------------------|
| tiny   | <=100MB            |
| small  | 100MB-1GB          |
| medium | 1GB-10GB           |
| large  | >10GB              |

**Comment by kelson42** [comment]
@automactic looks good to me

**Comment by kelson42** [comment]
Even if I wonder if it would not be simply better to give info about HW resources need at the time of the job scheduling and then start the docker worker with parameter specifying the HW limitation of the worker. Then the rest would run automatically with one queue (and filtering).

**Comment by automactic** [comment]
Celery does not work like that. If we have only one queue, then all free workers in the queue will get task evenly. A worker cannot say, let me inspect this task and if I don't like it then I will send it back.

Also, please define HW resources and limitations and how it is different from queue based solution.

**Comment by automactic** [comment]
This feature is being implemented in:
- #82 
- #85
