### ISSUE TITLE
Tweaks to Command line arguments display in Pipeline and Recipe

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#443]
In a task "command" field (in the "debug" tab), if I click on copy, the arguments on the strings are not double-quoted and therefore the command can not be run.

**Comment by rgaudin** [comment]
[dup command without docker in recipe]

**Comment by mahakporwal02** [comment]
@rgaudin Can you pls give me a proper example because I might have understood it but still need to confirm if we are on the same page

**Comment by mahakporwal02** [comment]
![Screenshot from 2020-11-03 17-00-41](https://user-images.githubusercontent.com/56486682/97980035-2bdd0f00-1df6-11eb-85c0-5370cfc6b67d.png)
![Screenshot from 2020-11-03 17-00-23](https://user-images.githubusercontent.com/56486682/97980042-2e3f6900-1df6-11eb-87e4-3b4b2f06d18d.png)
@rgaudin Pls see if this is what you meant above....and kindly elaborate the first bullet point

**Comment by rgaudin** [comment]
Yes, for the recipe part ; first one is about removing the Copy button on task view as this command is informational but not for reuse

**Comment by mahakporwal02** [comment]
@rgaudin pls review it

**Comment by mahakporwal02** [comment]
@rgaudin any updates??

**Comment by kelson42** [comment]
@mahakporwal02 Thank you for your PR, a few remarks about the usual workflow:
* I guess you ask a feedback your PR, then please leave a comment in the PR, not in the issue ticket
* Your contribution and enthusiasm are really welcome, but please leave a bit more time to people to answer you. Contributors are in different timezones and have multiple other stuff to do. They are partly even volunteers like you. Repository maintainers get a notification when you make a comment or leave a PR, they already know about the work do to. This repository has a stale bot configured at 7 days, as long as this does not get this "stale" tag, everything is normal and there is nothing more you can do on this ticket/PR. Usually you will get a feedback within a few (office) days.
* Last but not least, and this is not a judgment of the your PR at all (I'm not a Python developer). Reviewers are usually the most skilled and busy people in the project, so is @rgaudin. The better is your PR, the quicker it might be reviewed/merged because this does not need many times to look at it. Do your best to polish as much as possible your PR, my experience is that after a day or two, it might help to go through the PR code again to see if nothing can be improved again.
* Take a new task if you have free time (this is was you have done, great!)

**Comment by mahakporwal02** [comment]
Okay I will abide by the remarks for sure and sorry for being impatient I understand you guys are busy in lot other work...thanks for your guidance
