### ISSUE TITLE
Add Config tab in pipeline view

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#445]
When looking at a pipeline, the UI doesn't display the actual config that was used but instead provides a link to the recipe.

It's good for most cases but when a recipe has changed since that task, it's not accurate.

We shall add a _Config_ tab to the pipeline view that would mirror the one in the Recipe view, yet using the pipeline's own `config` data. Config should thus be extracted into a component and reused in both places.

**Comment by mahakporwal02** [comment]
@rgaudin Can you give me a proper example of this, I might have understood it but still need to confirm if we are on the same page

**Comment by rgaudin** [comment]
Sorry I did that a couple weeks ago and forgot to close the ticket.
