### ISSUE TITLE
Recipe history (old tasks) get lost by renaming

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#446]
Steps:
- rename a recipe with tasks in history

I get:
An empty history

I want:
To keep the history of pas tasks

**Comment by HAKSOAT** [comment]
Hello @kelson42 can you help with a pointer to the part of the code base that does this? I've spent some time trying to figure out on my own.

**Comment by kelson42** [comment]
@HAKSOAT Sorry, this is a question for @rgaudin, I'm not a Python dev.

**Comment by rgaudin** [comment]
That would be around https://github.com/openzim/zimfarm/blob/77d2117c8301a0333af50e30fd374dc281cc2ac0/dispatcher/backend/src/routes/schedules/schedule.py#L156

there's no such thing as renaming per say but a schedule's `name` can be updated, given the new name is not taken.
After that check, you would have to make sure that once renamed, you also change the `schedule_name` of `Tasks` and `RequestedTasks` for the previous name.

**Comment by HAKSOAT** [comment]
@rgaudin I just opened a PR #457 It took a while as I had to do a bit of understanding pymongo (not worked with it before). 

Also, is there any documentation that shows how I can setup zimfarm on my machine? I wasn't able to test the modification here, but I think it should work.

**Comment by rgaudin** [comment]
replied on the PR. No, there's no documentation and it's a bit of a pain (been there). We should document that though.

**Comment by HAKSOAT** [comment]
> 
> 
> replied on the PR. 

Seen. 

>No, there's no documentation and it's a bit of a pain (been there). We should document that though.

Yeah. It's been kind of hard to play around.
