### ISSUE TITLE
add 'zimfarm version' as option

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#447]
It would be nice, if there would be a command 'zimfarm version' to get the version/date of zimfarm.

I had an old version of zimfarm, did an update do and got an error. zimfarm was updated and the error is not reproducible now.

**Comment by kelson42** [comment]
@rgaudin I think you planned to do an autoupdate system... Do we have a ticket for that?

**Comment by rgaudin** [comment]
Yes that's #436 but that's for the manager. This specific issue concerns the script which we did not plan on versioning soon.

We'll add a simple version option for the script as well.

btw @JensKorte I know the bug you're mentioning as I discovered and fixed it. It was that the _update command_ lacked the `sudo` on the chmod part.

**Comment by JensKorte** [comment]
> We'll add a simple version option for the script as well.

Thanks!
 
> btw @JensKorte I know the bug you're mentioning as I discovered and fixed it. It was that the _update command_ lacked the `sudo` on the chmod part.

Nice! The lacking sudo could be suitable to the error message I saw.
