### ISSUE TITLE
zimfarm upload should request destination folder

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#455]
`zimfarm upload` on worker script should request (and guess if possible) the destination folder for ZIM files otherwise those will end up in `/zim` on download server.

**Comment by rgaudin** [comment]
Actually, now that #435 will remove data at task exit even if we had a ZIM file, we should probably remove the `zimfarm upload` feature altogether.

**Comment by kelson42** [comment]
@rgaudin Not sure to fully understand your last comment, but “yes” it seems we have to sort-out now this ticket.
