### ISSUE TITLE
Don't allow trailing space on recipe name

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#458]
ATM a recipe can be created with a trailing space resulting in the recipe not being reachable in the UI.

This should be fixed in both the UI and the backend.

**Comment by HAKSOAT** [comment]
@rgaudin I have a question regarding this... the schedules are the "recipes" right? 

Also I feel, the trailing space should be stripped away. Or should we outrightly throw an error?

**Comment by rgaudin** [comment]
That's right. Recipe is the _human_ name of the Schedule. It should be stripped away.

**Comment by HAKSOAT** [comment]
Great. Thanks.

**Comment by HAKSOAT** [comment]
@rgaudin I've opened a PR to fix this issue.

**Comment by kelson42** [comment]
If somehow could finish the work started by @satyamtg, that would be great.
