### ISSUE TITLE
check: Container not found

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#459]
Check if [#c0d21](https://farm.openzim.org/pipeline/5e6647b00ea60ccbedcc0d21/debug) is due to something we fixed after it was launched.

**Comment by kelson42** [comment]
new case https://farm.openzim.org/pipeline/5e85cab68fdff3cf73dbbdae/debug

**Comment by kelson42** [comment]
new case https://farm.openzim.org/pipeline/5e86ecef9f0a3aea0ddbd24b/debug

**Comment by kelson42** [comment]
new case https://farm.openzim.org/pipeline/5e7d2087d32b3fdd0ed459fe/debug

**Comment by kelson42** [comment]
My feeling is that this always happen with bigger content or/and with not so fast machines.

**Comment by rgaudin** [comment]
Ah ! that's helpful. Will look at it soon.

**Comment by kelson42** [comment]
New case https://farm.openzim.org/pipeline/5e885b480632de0fd0a1719c/debug

**Comment by kelson42** [comment]
An other one: https://farm.openzim.org/pipeline/5e908f892073bca32fde1673

**Comment by kelson42** [comment]
An other one I just have discovered, a bit older, but for which two ZIM files (usually it is only one) have not been uploaded because of this bug https://farm.openzim.org/pipeline/5e6b99b9b4a15e33625a5d15

**Comment by kelson42** [comment]
New case, interesting is that this is again WPRU all, https://farm.openzim.org/pipeline/5e89c7517d7ff07c15dbdbe2

**Comment by rgaudin** [comment]
Thanks for all the link @kelson42.

I could not find the root cause for this nor reproduce it but I've found several past issues of similar problems with ancient docket versions. Those were race conditions in docker.

I don't think it's a pure container race condition because we're only getting these on this particular image and never on dnscache or task or scraper… so there might be something in our image or the way we use it that have influence on that.

Based on those, I think that when this happens, the container is not gone but has never started. This means that instead of just uploading the last bits of the log, the next step would upload it completely. This should not be a problem in most case, but since we have a 20mn limit there, it might stop before sending the complete log on some cases (super large mwoffliner with verbose mode). I think it's OK as we've have the beginning and we always get the tail.

It's not caught and should not prevent the task from pursuing its task.
I am deploying it now so we shall expect task started after Apr 15 2020 12:00PM to not be affected.

I am opening a separate issue to consider not killing uploaders when we crash or stop.
