### ISSUE TITLE
Test task recovery

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#46]
Task needs to be recovered / rerun in the following cases:
- a worker running the task went offline
- a task failed (within the retry count)

**Comment by kelson42** [comment]
@rgaudin @automactic Is that not already the case now?

**Comment by rgaudin** [comment]
These two needs are irrelevant as we've moved to a schedule-less mode and run everything every month.

I've added a page [on the wiki](https://wiki.kiwix.org/wiki/Zimfarm/schedule) to document this important information.
