### ISSUE TITLE
feature request: support farm.o.o/worker#<workername>

### ISSUE THREAD

**Issue by JensKorte** [openzim/zimfarm#461]
I don't know, if this is possible with dynamicly generated pages.

It would be nice, if I could jump to or highlight the worker(s) that match the anchor in the URL.

e.g.: https://farm.openzim.org/workers#hum would jump to the worker hum (exact hit) or it would highlight all worker containing "hum".

Nearly the same can be done with the search function in the browser, but with #hum it would be a permanent URL that can be bookmarked and shared.

**Comment by mahakporwal02** [comment]
@rgaudin Can I work on this issue??

**Comment by kelson42** [comment]
Looks good!

**Comment by rgaudin** [comment]
Sure! Please let us know how/what you plan to do first as this is not clear what's exactly expected from this ticket.

**Comment by mahakporwal02** [comment]
I plan to extract the string after hash('#') in url after '/workers' then find that substring in the worker's name, if the substring is present then a css class will be applied on that substring which will change the background behind that substring to a different color

**Comment by kelson42** [comment]
@mahakporwal02 This isnot how itshould work IMO, read thi for example http://www.echoecho.com/htmllinks08.htm

**Comment by mahakporwal02** [comment]
@kelson42 should the webpage just scroll down to worker name or should the worker name be highlighted as well?

**Comment by kelson42** [comment]
@mahakporwal02 Jumping to seems good enough. If you can do high,ight as well, that might be nice... But I don't know how this would be doable in a simple manner (with a simple CSS rule). Therefore, probably not worse it.
