### ISSUE TITLE
Zimfarm should provide a way to see the log trail during the scrape

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#462]
For the moment:
* The logs are uploaded regularly to the warehouse during the process
* The trail of the log is only visible if the task is finished

This would be great for example to be able to see "live" what is going one (identify a stuck task for example). Web page could be auto-update as well. I think we should have a way to be able to easily see that.

This might be linked to #373 and #331

**Comment by rgaudin** [comment]
You have the donwload log button from the moment the log is created.

If you're concerned about something progressing or not, you can click on it and get the full log (with its latest part).

It's not very pretty (raw docker json log) but taking 30s to look at it (or pass it through `jq -j '.log'`) and you'll have your information.

This answers your _identify if a container is stuck_ issue.

**Comment by kelson42** [comment]
@rgaudin yes, this is not really user-friendly.

**Comment by rgaudin** [comment]
This was deployed yesterday. Last 100 lines of both stdout and stderr are periodically uploaded
