### ISSUE TITLE
Where are zim file descriptions stored?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#464]
When I'm in the Cardshop, say for Dirty Biology (in French), I get the following:

![image](https://user-images.githubusercontent.com/21675885/77757200-10747f00-7031-11ea-8c10-cd4548b0d165.png)

Yet in the zimfarm the description line is empty. So where is this rather long text stored?

**Comment by kelson42** [comment]
I guess this comes directly from the youtube channel.

**Comment by rgaudin** [comment]
Yes, as for mwoffliner, there's an auto-description feature in case it's not set.

If the recipe is a channel, it's the channel description, if it's a playlist it's the playlist description (many playlists have no description though) and if a list of playlists, it's the description of the first one.

If after all that, it's still empty, then it's set to `-`.
