### ISSUE TITLE
keep ZIM uploads running after stop ?

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#468]
In a zimfarm task, ZIM files are created by the scraper and then directely uploaded, one at a time ; launching an uploader container.

We stop those upload containers on the following circumstances:
* task worker crash (different than scraper).
* task worker halted (`docker stop` or `docker kill`)

We could imagine that given the nature of the zimfarm (creating ZIM), we consider that `docker stop` should stop the task but leave the ZIM file uploader alive…
We could also apply the same behavior on task-worker crash.

**Pros** :

* don't loose existing, started to upload ZIM file on crash. It should be rare but it can happen.
* don't loose existing, started to upload ZIM file on manual stop or cancel. rare also but happens.

**Cons**:

* Unexpected behavior? When you `stop` or `cancel`, you might expect everything to stop. We do have `kill` option to separate those concepts.
* It would only work for _started ZIM uploads_, not for pending-upload ones. Imagine you have 2 ZIM files created and the task worker started uploading one then you stop: only the first one will continue but the second one would never be started.

Note that this last scenario would be very unlikely as this would require first ZIM to take more time to upload than the scraper would take to create the second one… might only happen on very small ZIM for which it's less of a problem.

So @kelson42, what do you think?

**Comment by kelson42** [comment]
All of this is a bit subtil... and scraper should not die ;) This is the most important. But "yes" created ZIM file should ideally always be uploaded properly. So, I'm in favour of that ticket, but does not sounds to be a priority to me.

**Comment by Jaifroid** [comment]
I don't know if this is the same issue, but I've been waiting for `wikipedia_en_medicine_maxi_2020-07.zim`, and got excited when I saw that ZIMfarm made a copy this morning and (apparently) uploaded it to download.kiwix.org. Only it's not there, even though ZIMfarm shows it to have uploaded: https://farm.openzim.org/pipeline/5efc2da09ec57a81057992e9. The other four medicine ZIMs from 2020-07 are all there, but not this one. There is an exit code of 0 in the debug -- not sure if this signals success or failure. Apologies if this is not related.

**Comment by kelson42** [comment]
@Jaifroid No this is an other "problem", the ZIM go through a quarantine and this might take a few hours. See https://github.com/openzim/zimfarm/issues/476

**Comment by Jaifroid** [comment]
Ah, OK, thank you!

**Comment by kelson42** [comment]
@rgaudin I believe we will have to fix that ticket by integrating the zimquarantine to the zimfarm, as th upload is beetween the scraping itself and the quarantine.

**Comment by rgaudin** [comment]
After discussing this with @kelson42, decision is to keep current behavior: on stop, we stop everything.
Those events are too rare for this to become problematic and it relieves us from handling a special behavior.
