### ISSUE TITLE
Periodic scheduling of past failed tasks might be improved

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#469]
Goal of the Zimfarm is to provide up2date quality ZIM files without a human effort.

For many reasons tasks can fail. Even if the situation is improving rapidly we will always have this kind of tasks.

This morning I had the following situation:
* No tasks in TODO
* Many (Wikipedia) recipes (with a monthly rescheduling) which had last task failed one or even two months ago

I had to reschudle part of them manually whereas I think they should have already been scheduled automatically.

I don't know exactly what should be done, but I believe I should not have to do that work manually.

**Comment by rgaudin** [comment]
OK, it's not very actionable at the moment. Can you share the names of those recipes so that I can check whether we need to change our requirement or if it's a bug in implementing it.

**Comment by rgaudin** [comment]
I've checked all those you started today and none corresponds to what you said. All those had a task 25 days ago (26 for one). As you know, the trigger is 31 days.

We've already discussed whether a task which failed should be automatically rescheduled _before_ that time trigger and it was decided not to. So it's working as specified so far.

Now that we have had successful runs for most tasks, we may want to tweak the behavior a bit. We should probably discuss it in a meeting and document changes.

**Comment by kelson42** [comment]
Yes, probably everything works as intended.

But it might be better to speed up (schedule now) scrapes (part of them at a time) which would have been done anyway within the same month (with a priority to the one which have fail last time) if todo list is empty.

This would not really complexify current scheduling. This is an extension of the periodic auto scheduler. This would allow, if our HW resources allows it, to move automatically tasks earlier in the month... Which is good (ideally all tasks for March would be done the 1st).

**Comment by rgaudin** [comment]
OK, so I guess we should define when we're in under-load. That could be a mixture of nb of tasks in the pipe and resources available (from the workers).

then we could have a different scheduling:
* run only failed task (otherwise we could have date conflict in filename)
* run only if a fraction of the period has passed (40%?)

Keep in mind our monthly scheduling (as others) is not bound to calendar months but to a 31days period since last task. So each recipe has its own period.

**Comment by kelson42** [comment]
I believe there is nothing much we can do here because:
* We don't want to make any assumption about the filename (start or end of the scrape)
* I'm not really happy to have a retry mechanism around a week for example for failed tasks.
