### ISSUE TITLE
Clear roles and permissions

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#479]
ZIMit will probably need additional permissions/roles. Before we follow such a path I would like to clarify/document/implement a few things:
* What is the motto/definition of each role (should be visible from the UI)?
* Where is the list of available permissions with definitions (should be visible from the UI)?
* What are the permissions associated to each role (should be visible from the UI)?
* Are specific features associated properly to permissions (and not roles)?
* Is it clear/documented/clean in the code how to (de-)associate permissions to roles?

**Comment by rgaudin** [comment]
> ZIMit will probably need additional permissions/roles. Before we follow such a path I would like to clarify/document/implement a few things:
> 
> * What is the motto/definition of each role (should be visible from the UI)?

Issue #433

> * Where is the list of available permissions with definitions (should be visible from the UI)?

On users page (#433 to improve)

> 
> * What are the permissions associated to each role (should be visible from the UI)?

users page but users could have additional permissions. #433

> * Are specific features associated properly to permissions (and not roles)?

yes

> * Is it clear/documented/clean in the code how to (de-)associate permissions to roles?

yes

**Comment by kelson42** [comment]
@rgaudin Thx, I have elaborated a bit the requirements for #433 and will close that one as duplicate.
