### ISSUE TITLE
Implement quotas for users

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#481]
We need to be able to limit a user to a certain level of resource usage. It is not clear at which level and how for the moment.

**Comment by rgaudin** [comment]
what does this mean ? what is a resource usage for a user ?

**Comment by kelson42** [comment]
We need at the same time to allow a proper Zimit UI UX (proper resource sharing) and forbids that one full system (like the Zimit UI) to not take all the Zimfarm HW resources for itself. I'm not sure which form it should take in general and in particular at the Zimfarm level. It could take the form of HW resource quota but this could as well be a time quota.

**Comment by rgaudin** [comment]
So the user requesting a task would be the (future) consumer (once it is started on a worker).
Obviously, segregating by user would not be practical so we'd have to add another layer (group/org).

**Comment by kelson42** [comment]
@rgaudin the "user" here would be something like "zimit_ui", so not an hypothetical end user of the Zimit UI system.

**Comment by rgaudin** [comment]
Yes, so a user of the zimfarm. But you don't want to set quotas to both kelson and stephane. You want to set quota for the zimit group and for the openzim group. That's what I meant, not zimit-users.

**Comment by kelson42** [comment]
Yes, a user of the zimfarm but not sure we are on the same page for the rest.

The workers do the ZIM files. Here the user requests a ZIM (so create a recipe, instanciate a task of if and track its execution). It does not "consume" a task but create it. I think we can call them "requester" and this would be indeed (probably) a new role (I have updated #482). Therefore, I don't think this is a good idea to talk about users "stephane" or "kelson" which have already predefined roles (and don't need quota indeed... but they could have an infinite quota?!).

Regarding the group, you seem to believe mandatory, to me this is not clear why we should create this concept. This is probably worth a separate ticket. But in the meantime, "yes" I want to create a limitation/quota on a user and the one and only unique "zimit_ui" user would be the first one to "benefit" of this feature.

**Comment by rgaudin** [comment]
From what you say, I still understand that the _object_ responsible for resource consumption is the _requester_ of a task. It's important we agree on that part.

Currently, requesters of tasks are users.

So either we change that (it's possible), or we'll have to assign quotas to users (regardless of their role). I agree we don't need a _container_ to store quotas in but then it's limited to per-user quota (with defaults to unlimited).

**Comment by kelson42** [comment]
> From what you say, I still understand that the _object_ responsible for resource consumption is the _requester_ of a task. It's important we agree on that part.

yes

> Currently, requesters of tasks are users.

yes

> So either we change that (it's possible), or we'll have to assign quotas to users (regardless of their role). I agree we don't need a _container_ to store quotas in but then it's limited to per-user quota (with defaults to unlimited).

Make sense and then probably almost all users we have so far will have unlimited quota. But we could also say that quota is take in account only for a certain role.

**Comment by kelson42** [comment]
@rgaudin We don’t need that anymore. For ZImit, we just you an option of the zimit scraper. I propose to close as WONTFIX.
