### ISSUE TITLE
Implement "requester" role for a third party system like the Zimit UI

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#482]
Do we have such a system/user/role should at least:
* Be able to manage its own recipes/tasks?
* Don't touch other user recipes?

Related to #479

**Comment by rgaudin** [comment]
We don’t.

**Comment by kelson42** [comment]
@rgaudin We had the generic requirement in #479 and the specific one for Zimit here. Considering that we are just creating a private Zimfarm for Zimit, we don’t need this specific ticket anymore. But the generic requirement is still valid. Therefore, I propose to:
* close this ticket as WONTFIX
* reopen #479, but not in Zimit project.

**Comment by rgaudin** [comment]
I don't see anything in #479 that is not already on other tickets so I won't reopen it (it's not actionable). Add some content and reopen if you feel there is something.
