### ISSUE TITLE
ZIM files should be sorted by creation date on task view

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#486]
It seems in the Web task view, that the list of created ZIM files is not sorted. It should be sorted chronologiquely.

**Comment by rgaudin** [comment]
which we. task view ? which chrono order ?

**Comment by mahakporwal02** [comment]
@kelson42 I am interested in solving this issue....can you please elaborate about this issue,what does web task view means

**Comment by mahakporwal02** [comment]
@rgaudin any updates please?

**Comment by mahakporwal02** [comment]
![Screenshot from 2020-10-29 21-40-16](https://user-images.githubusercontent.com/56486682/97600735-624e0f00-1a2f-11eb-86d2-a05142849ac4.png)
@rgaudin @kelson42 Zim files are sorted chronologically....pls take a look at it
