### ISSUE TITLE
Durations rounding is misleading

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#487]
See:
![image](https://user-images.githubusercontent.com/1029718/82871577-1a800480-9f32-11ea-9835-ab0c257e4113.png)

Duration should be: 3 hours + 17 mn + 2 hours... but it is 3 hours. Something is wrong here because ZIM files are here not build in paralell.

**Comment by rgaudin** [comment]
OK so the total computation time (`Duration: 3 hours`) appears to be less than the sum of all the ZIM files creation (which are run one after another).

This is not a computation error. This duration is just the duration between `started` and `scraper_completed`.

The issue is with the rounding of the value done by [moment.js](https://momentjs.com/docs/#/durations/humanize/) which is not precise enough.

Maybe we should not use `humanize()` for durations and use a short string like `02:17:36` ?

**Comment by mahakporwal02** [comment]
I am sorry about directly making this PR without mentioning anything earlier here....kindly assist me to go ahead with this PR

**Comment by rgaudin** [comment]
That's OK ; will look at it tomorrow. thank you

**Comment by mahakporwal02** [comment]
@rgaudin any updates??

**Comment by mahakporwal02** [comment]
@rgaudin So does this mean the duration has to be shown without rounding off for instance if the duration is 91mn it should display "01:31"??

**Comment by rgaudin** [comment]
@mahakporwal02, I'm not the one who opened the ticket. @kelson42 did.

**Comment by kelson42** [comment]
My ticket complains about two things:
* rough rounding (legitimate)
* values, but I misunderstood how it was working. After @rgaudin’s comment I unerstand better (not legitimate)

Concerning the rounding, I want to precise my request. The values given here need:
* to easily give a good sense of the duration
* has to be easily compareable to previous runs

Therefore, I believe we should print durations with « two decimals », which gives in the hour system something like:
* 2d 2h
* 5h 30m
* 30m 2s
* 10s

So no rounding anymore, but scientific precision truncating.

Implementing https://github.com/openzim/zimfarm/issues/486 would help as well to better understand these numbers.

@mahakporwal02 Hope this helps

**Comment by mahakporwal02** [comment]
![Screenshot from 2020-11-01 00-39-23](https://user-images.githubusercontent.com/56486682/97787875-c19c5280-1bda-11eb-8911-5325e5e2a751.png)
@rgaudin @kelson42 Is this fine?
Can I make a pull request?

**Comment by rgaudin** [comment]
Looks good

**Comment by mahakporwal02** [comment]
@rgaudin @kelson Pls review it
