### ISSUE TITLE
Quarantine should check the ZIM file name

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#501]
It should match this PCRE regex expression:
```
/^(.+?_)([a-z\-]{2,10}?_|)(.+_|)([\d]{4}|)\-([\d]{2})$/i
```

**Comment by satyamtg** [comment]
This can be done in a couple of ways. What I think would be good is -
```
check if zim is valid or not
if valid:
    check file name:
    if valid:
         put to dest
   else:
        put to quarantine_dir/invalid_name
else:
    put to quarantine_dir/invalid_signature
```

@kelson42 @rgaudin what do you say?

**Comment by rgaudin** [comment]
https://github.com/openzim/zimfarm/blob/5a4b16ee3c17cee52091790cbb59979a70d66013/receiver/apps/check_zim.sh#L45-L52

Think we should just add the filename test on line 47. and place to quarantine if wrong. What's important is that we add the correct message to the log.
