### ISSUE TITLE
In online recipe view, languages are not sorted properly

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#502]
In edit mode of a recipe, the select box of the languages is not sorted properly.

**Comment by rgaudin** [comment]
Well this is not much actionable. What's properly in this case? How would you want it sorted?

At the moment, languages list in edit is the same as languages list in recipes listing. It is sorted by language code.

Please give your sorting preference for edit and listing (I believe you'd want the same) and also, should that be applied to the [API endpoint](https://api.farm.openzim.org/v1/languages/) or just in the UI?

**Comment by kelson42** [comment]
alphabetical order is the proper order.

**Comment by rgaudin** [comment]
Sorry I didn't realized you had to pay money for each character you write 😂
It is already on alphabetical order. Do you mean on the language name ?

**Comment by kelson42** [comment]
It is not sorted properly in alphabetical order:
![image](https://user-images.githubusercontent.com/1029718/85377037-cec47900-b538-11ea-9a85-3f10de69199e.png)

The ordering by iso code is not the same as per language (what this this selectbox/ticket is about).

**Comment by rgaudin** [comment]
So, as I wrote, currently we are sorting alphabetically on the language code (ISO-639-3).

What you want (I think) is it sorted alphabetically on the language name.

Last question still applies: Should this be changed on the API endpoint (which is used directly in the UI) or should the endpoint keep current ordering and the sorting on name be done only in the UI?

**Comment by kelson42** [comment]
> Last question still applies: Should this be changed on the API endpoint (which is used directly in the UI) or should the endpoint keep current ordering and the sorting on name be done only in the UI?

I don't know, I don't know the implication of each part of the alternative. If no other implication, I believe I would prefer to have the list sorted properly in the API.

**Comment by rgaudin** [comment]
OK, works for me. We don't use it anywhere else and I doubt we have user relying on this order (if we have users at all!)
