### ISSUE TITLE
Wrong ZIM file temporary name

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#51]
Newer version use foobar.zim as temporary file to write the ZIM file. This is a regression in comparison to the previous version and does not allow anymore to know if a ZIM file is ready or not. foobar.zim should be named foobar.zim.tmp as long as not everything is over with its creation. Then it should be renamed.

**Comment by automactic** [comment]
@kelson42, are you talking about the offliner generating zim file process or the ftp file uploading process? If the former, the offliners are responsible of the file name; if the latter, I need to further investigate. 

Also, why did you tag @mgautierfr?

**Comment by kelson42** [comment]
This issue was moved to openzim/zimwriterfs#52

**Comment by kelson42** [comment]
@automactic Sorry, wrong repo.
