### ISSUE TITLE
Web Recipe list filters should be in URL

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#510]
This would allow to share URLs, create bookmarks, etc...

**Comment by Abuhmadh** [comment]
Good

**Comment by DanielMK01** [comment]
Hi @kelson42 ! I'm interested in working on this issue, but I would like clarification on a couple of things.

1) Which file(s) should be updated for this issue?
2) Is there any other set-up for the project required besides the procedure shown in the Contributing.md file?

Thanks!

**Comment by kelson42** [comment]
@DanielMK01 Thank you for proposal but I'm not the lead developer here and the lead developer is away for a few days, but you will get a feedback lately Monday next week.

**Comment by DanielMK01** [comment]
@kelson42 I see. Who is the lead developer?

**Comment by mahakporwal02** [comment]
@kelson42 @rgaudin Can I work on this issue?

**Comment by kelson42** [comment]
@mahakporwal02 I believe this is slightly more complex than what you have done so far. Please explain here your plan to fix it before starting the coding.

**Comment by mahakporwal02** [comment]
@kelson42  First I am planning to add filters to url using `this.$router.replace` and when the page is reloaded I am accessing the queries from previous url using `this.$route.query.<filter>` and pushing the filters into `selected<filters>` function in `schedulesList.vue`

**Comment by mahakporwal02** [comment]
@rgaudin This issue might have been left open
