### ISSUE TITLE
Inaccurate ZIM size shown on zimfarm

### ISSUE THREAD

**Issue by satyamtg** [openzim/zimfarm#515]
In run https://farm.openzim.org/pipeline/5f08b8d3a96db4d3a3808ecc , the ZIM size is 456MB in size but on the Zimfarm UI it shows 23.28 MB only. This seems to be rather a bug.

**Comment by rgaudin** [comment]
This is most likely a zimwriterfs/libzim bug creating the ZIM file before it is complete (which is not allowed).
It should have, as before, create everything and just renamed it to ZIM so it's atomic: you have a .zim file and it won't change.

@kelson42

**Comment by kelson42** [comment]
@rgaudin What are the next steps.

**Comment by rgaudin** [comment]
https://github.com/openzim/zim-tools/issues/116
