### ISSUE TITLE
Create /zim/videos folder

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#520]
We're having an increasing number of videos, particularly with the new Playlist feature. It would be useful to have them sorted in /videos (or /youtube?) rather than /other

**Comment by kelson42** [comment]
I'm I believe in favour of the creation of somethin like `/zim/videos` (I talked a few times in the past about that). @rgaudin Should we?

**Comment by rgaudin** [comment]
I'm against a `youtube` one but I think a `videos` one could be helpful. I'd like to have a clear definition of what would go there before we implement it so that we don't have to discuss destination on per-ZIM basis (exceptions always occurs though).

**Comment by Popolechien** [comment]
> I'd like to have a clear definition of what would go there

Let's make it simple: if the main piece of content is video-based (e.g. Youtube, as opposite to OpenEdx where video is just a feature), then it goes in there. Ideally any random user should be able to understand what they'll be looking at.

**Comment by rgaudin** [comment]
Works for me. Creating it. @kelson42 should we move existing ones?

**Comment by kelson42** [comment]
@rgaudin I don't believe we need to move the existing ones... the recipes should be updated... and I hope the old ones will be deleted automatically. Crossing the fingers...

**Comment by Popolechien** [comment]
@kelson42 slightly different but I deleted a recipe once and the zim files are still there. (recipes that created http://download.kiwix.org/zim/other/aimhi_en_philosophy_2020-06.zim and http://download.kiwix.org/zim/other/aimhi_en_geography_2020-06.zim were replaced when we created the playlist and are now older duplicates of aimhi_geography_2020-07.zim and aimhi_philosophy_2020-07.zim    )

**Comment by kelson42** [comment]
@kelson42 These new filenames are not valid.
@rgaudin We should do something to avoid that, I see in https://download.kiwix.org/zim/other/ a lot of "random" filenames I guess generated by the Youtube scraper. We should do something quick to fix and avoid this.

**Comment by rgaudin** [comment]
@kelson42 I think we can close this ; right?
