### ISSUE TITLE
Quarantine should check if ZIM filename matchs the norm/regex

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#522]
To avoid random filenames coming from broken scraper or bad recipes.

**Comment by rgaudin** [comment]
Can you provide the regexp? or criterias?

I think the main format is `<source>_<lang>_<selection|flavour>_<period>` with:

* `<lang>` being ISO-639-1
* `_<selection_flavour>` optional
* period is `YYYY-MM` format

**Comment by satyamtg** [comment]
@rgaudin @kelson42 didn't we do it while solving #501? The issue had a regexp there. In what ways solving this would be different from that?

**Comment by rgaudin** [comment]
Ah right!
