### ISSUE TITLE
Table columns on Recipes page are misaligned

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#528]
I just realized that there is an extra column in the recipe column (after the _Offliner_ column) and that causes the header row's last two columns to be misaligned
![Capture d’écran 2020-09-09 à 14 26 58](https://user-images.githubusercontent.com/21675885/92598168-beef4200-f2a8-11ea-9505-7b43f51f6830.png)

**Comment by rgaudin** [comment]
I don't see any problem in the screenshot (or that's how we designed it).
If you're referring to the fact that there are two columns under a single column header (last task), that's on purpose : we have two information for the last task (it's status and the date). We thus merged the two headers in one.

If that's something else, please be more explicit.

**Comment by Popolechien** [comment]
Ah ok then it's a little bit unclear what the watch icon is here for, I thought it was meant to be on top of the started/succeeded one.

If `Last Task` is meant to cover two columns, maybe we should center it then.

**Comment by rgaudin** [comment]
the watch hosts an icon if the recipe is currently scheduled (in the todo pipe).

There should be some basic info when you mouse over the icon.

**Comment by Popolechien** [comment]
Ok. Could probably be improved on but thanks for the clarifications.
