### ISSUE TITLE
Enhanced File Transfer

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#53]
Currently we use plain FTP to transfer files from worker to warehouse. This brings a security risk, as username and user token are transferred in plain text. 

We also had a discussion regarding using rsync. The problem is it is not possible to enter the password programatically. 

------

Here I propose another approach, inspired by GitHub. (thanks @blajzer)

- User upload their public key to dispatcher, who then store the key in database. (like the [GitHub key management system](https://github.com/settings/keys))
- Worker map `~/.ssh` on host to the same path inside of the container on startup
- Warehouse is a ssh server implemented using [Paramiko](http://docs.paramiko.org/en/2.4/index.html)

When worker need to upload a file:
1. worker use rsync over ssh or SFTP, which at some point a ssh connection is required
2. warehouse receive the ssh auth challenge 
3. warehouse send a request to dispatcher try to verify the username and key
4. dispatcher query its database, verify or reject the username and key
5. warehouse accept or reject the auth challenge

**Comment by kelson42** [comment]
Sounds reasonable to me.

**Comment by automactic** [comment]
Finished in PR #57
