### ISSUE TITLE
Investigate scraper stalled

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#530]
Task [#698fd](https://farm.openzim.org/pipeline/5f55f6c69c7604d0738698fd) on athena stalled on 2020-09-07T13:43.

```
{"log":"[log] [2020-09-07T13:43:29.605Z] Progress downloading articles [48530/49995] [97.1%]\n","stream":"stdout","time":"2020-09-07T13:43:29.605512354Z"}
```

Task [#fe986](https://farm.openzim.org/pipeline/5f5620c4ce69780c208fe986) on mwoffliner2 stalled 2020-09-07T13:43.

```
{"log":"[log] [2020-09-07T13:43:31.593Z] Progress downloading files [76410/81851] [93.4%]\n","stream":"stdout","time":"2020-09-07T13:43:31.593448612Z"}
```

Both are mwoffliner tasks and both stalled at exactly the same moment, which may indicate an outside event as the cause.

Uptime robot tells me that it detected the zimfarm API to be offline at 13:47:29 and the downtime lasted for about an hour.

There should be no relationship between the scraper (an independent container) and the API but there might be an unknown side-effect on the whole docker when the manager and the task workers can't talk to the API.

**Comment by kelson42** [comment]
Interesting... From the outside it looks as well pretty much at the infamous problem we had with mwoffliner which was stuck almost at the end... but the same date of last log entry can not be a coincidence.

**Comment by kelson42** [comment]
Not sure we have seen this patern recently...

**Comment by rgaudin** [comment]
Agrees. Let's close it.
