### ISSUE TITLE
Unable to categorize videos as videos

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#532]
Looks like it is not possible to categorize Youtube zim files as videos in the recipe dashboard
![image](https://user-images.githubusercontent.com/21675885/93011926-94003900-f59b-11ea-88f8-d3d4e92fff16.png)

**Comment by rgaudin** [comment]
There are multiple classifiers:
- zimfarm tags. pretty flexible but only used in zimfarm.
- ZIM tags. also flexible but not used to sort zims in any reader at the moment I think.
- ZIM categories. not flexible, hard coded in both readers and the zimfarm. this is the base of the zim browsing in ios. we rarely touch this.
- Warehouse path. Not much flexible, hard coded in zimfarm. this is the folder where zim are stored. doesn't affect readers.

We added a videos warehouse path recently but not a category.

**Comment by Popolechien** [comment]
I asked because I saw that aimhi was stored in `other` but then it's two months old so maybe that was before the warehouse was created (I've restarted it as there seem to be a bug)

**Comment by kelson42** [comment]
Aihmi filenames are still wrong as well....
