### ISSUE TITLE
Cannot create balinese (ban) recipe

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#535]
We got a mail from a Balinese Wikipedia (ban.wp) user asking why we did not offer their language projects (4k articles): when I went to create a recipe... balinese was not an available choice (In the language selectbox).

**Comment by kelson42** [comment]
Please create the `wikipedia_ban` recipe as soon as this bug is fixed.

**Comment by rgaudin** [comment]
You can even create it before with a different language and leave it disabled for now

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/wikipedia_ban_all based off ab.wp recipe.

**Comment by rgaudin** [comment]
Done

**Comment by Popolechien** [comment]
Ah, I launched the recipe and it failed with this odd message: 
`(node:12) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`

Should I open a separate ticket or is it benign (and mostly of my own doing)?

**Comment by rgaudin** [comment]
That's mwoffliner…

**Comment by rgaudin** [comment]
Ah no actually it's been killed by docker. Maybe not enough RAM. @kelson42 can you follow-up ?

**Comment by kelson42** [comment]
yes, indeed there was not enough RAM

**Comment by Popolechien** [comment]
Ok, this worked this time. Thanks
