### ISSUE TITLE
pipeline/filter-failed does not display "last run" info anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#542]
It seems this is because a recipe has been renamed (`katabiblon`?) and then it breaks everything.

**Comment by rgaudin** [comment]
Was actually fixed in ef25f58c8 but issue was not linked properly.

**Comment by rgaudin** [comment]
For the record, the problem is indeed if a schedule has been renamed, it couldn't fetch status of its last task and failed due to incorrect schedule name.
Reopening as a delete schedule (although very rare) would raise the same.
