### ISSUE TITLE
problem in setup installation

### ISSUE THREAD

**Issue by mahakporwal02** [openzim/zimfarm#543]
[//]: # (Pick appropriate classifiers)
- Location: __U.I | API | Worker | Wharehouse | Output ZIM__
- Schedule Name/ID: __n/a__
- Task ID: __n/a__

## Problem

[//]: # (1)Terminal closes once we paste the script of workers given in contributing.md 2)my frontend and backend are working propertly but pipeline in frontend doesn't show tasklist in any of the four options (TODO,DOING,DONE,FAILED) )

## Reproducing steps

[//]: # (Information on how to reproduce it.)

**Comment by kelson42** [comment]
Please share the terminal command and output.

**Comment by mahakporwal02** [comment]
`cd workers
cont_name="zimfarm-manager"
echo "building task-worker"
docker build . -f task-Dockerfile -t task-worker:local || exit 1
echo "building working-manager"
docker build . -f manager-Dockerfile -t worker-manager:local || exit 1
docker rm $cont_name
docker run \
	--name $cont_name \
	-v $(pwd)/worker-data:/data \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	-v /home/self/.ssh/zimfarm:/etc/ssh/keys/zimfarm:ro \
	--env ZIMFARM_CPUS='3' \
	--env ZIMFARM_MEMORY='2G' \
	--env ZIMFARM_DISK='2G' \
	--env SELFISH="y" \
	--env USERNAME='admin' \
	--env DEBUG=1 \
	--env WORKER_NAME="myworker" \
	--env POLL_INTERVAL="30" \
	--env PLATFORM_wikimedia_MAX_TASKS="1" \
	--env PLATFORM_youtube_MAX_TASKS="1" \
   --env WEB_API_URI="http://192.168.5.80/v1" \
	--env TASK_WORKER_IMAGE='task-worker:local' \
	worker-manager:local`
I entered this command and the terminal abruptly shuts down

**Comment by mahakporwal02** [comment]
![Screenshot from 2020-10-24 17-08-21](https://user-images.githubusercontent.com/56486682/97080796-b74ae900-161b-11eb-91f2-152797d38f94.png)
There is no information shown about tasks in any the four filters(TODO,DOING,DONE,FAILED) but the recipes are working properly
I have to test changes i have made in the frontend code

**Comment by kelson42** [comment]
@mahakporwal02 One problem per ticket please.

**Comment by kelson42** [comment]
@mahakporwal02 https://docs.docker.com/engine/reference/run/#detached-vs-foreground ?

**Comment by rgaudin** [comment]
Without terminal output, it's not possible to assist you with this. Might be a terminal or shell issue.
Are you familiar with running docker containers?

**Comment by mahakporwal02** [comment]
![Screenshot from 2020-10-26 15-12-14](https://user-images.githubusercontent.com/56486682/97157105-aa560300-179d-11eb-8e76-981156a6b034.png)
![Screenshot from 2020-10-26 15-12-10](https://user-images.githubusercontent.com/56486682/97157111-ac1fc680-179d-11eb-992f-fa160302a43c.png)
This particular command is not working
@rgaudin @kelson42

**Comment by rgaudin** [comment]
OK this command is OK to fail the very first time as the container has not been created You can continue.
