### ISSUE TITLE
Feature request: Worker-Manager dynamic resource limit

### ISSUE THREAD

**Issue by kevinmcmurtrie** [openzim/zimfarm#551]
It would be helpful to issue zimfarm commands to dynamically adjust resources consumed by scrapers.
Use cases:
- Pause all work while running on backup power or a backup Internet connection
- Reduce or increase the load according to room temperature
- Reduce workloads when the client needs to perform other work

Running on UPS is my biggest concern now.  I may create a script to issue "zimfarm shutdown" when power is lost, which will lose progress on tasks that may have been running for several days.

BOINC has similar features that can be used to limit its interference.  Typical zimfarm runners are going to be technically proficient so the detection features can be omitted.

**Comment by kelson42** [comment]
I'm not sure this is a good idea if we have workers which change regularly the level of resources available or even put tasks on stop/pause. The granularity of tasks if pretty low and to be able to run them properly we need a good forecast, predictability and stability of workers.

**Comment by rgaudin** [comment]
That's an interesting feature but I don't think we really have a need for it nor we want to maintain it:
- most workers are dedicated. yours is an exception
- we don't know how our scrapers nor the rest of the stack behaves on `docker pause`. That's definitely something we should study and document.
- adjusting the resources of running workers, while possible is not something we want IMO. As @kelson42 said, it's more important for us to be able to predict a task ETA. Which we do by metering duration and use in the scheduler.
- it's possible to change the resources affected for new tasks by changing the config file and `zimfarm restart`. Should the pause/unpause work properly, that should be suffiscient for your whole use case.

I'm gonna close this as wontfix. We should create a ticket to document pause/unpause and in the mean time, I think it's safe to trigger a `zimfarm shutdown` on your UPS event.
