### ISSUE TITLE
Impacted by new Docker hub limits

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#553]
https://farm.openzim.org/pipeline/5fafff48d19a61b9b76fa60b/debug

**Comment by kelson42** [comment]
A proposal:
* worker can check local image tag anf if match the one request by the recipe, then don’t pull
* in the task we need to be able to force a pull (for dev tag or in case of image overwritting)

**Comment by kelson42** [comment]
@rgaudin part of the problem is the uploader container.... which has no version tag....

**Comment by rgaudin** [comment]
OK, here's the situation:

- [Limits](https://docs.docker.com/docker-hub/download-rate-limit/) are per-IP (so per worker) on unauthenticated requests (our case).
- Limit is 100 req per 6 hours.

Here's a summary of our pulls:

Image | Requests (current) | Requests (new)
------------ | ------------- | ----
`worker-manager` | one on worker start | Idem (negligible)
`task-worker` | One per task on task launch | `1/t` required to update worker code
`dnscache` | One per task on task launch | `0` Will be pulled once then kept. Never gets updated
`scraper` | One per task on task launch | `1/t` we'll pull always to make sure we update tags like `:dev`
`uploader` | Many. one each time uploader is fired (many many time to handle progression) | `0` Will be pulled once then kept. Never gets updated

New total per task: `~2`
