### ISSUE TITLE
Zimfarm incorrectly labels zim language to english

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#563]
Just noticed that both PHZH OpenedX MOOCs in Arabic and Greek are labeled (and found) as English
https://farm.openzim.org/recipes/phzh_core-arabic-one
https://farm.openzim.org/recipes/phzh_core-greek-one

![Screenshot_20201126_165219](https://user-images.githubusercontent.com/21675885/100371964-e08ada80-3008-11eb-8c1a-92ec94f7825e.jpg)

**Comment by rgaudin** [comment]
This (the `Language` tag of the ZIM) is not handled by the zimfarm. It is set by the scraper (usually via a `--language` option that you specify in the recipe).
There doesn't seem to be such an option for openedx scraper so you should open a ticket there to request it.

**Comment by Popolechien** [comment]
move /openzim/openedx
