### ISSUE TITLE
Circumvent pull-rate limits

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#586]
While we've greatly decreased our images pulls in #553, we are still very much affected by [the limits](https://www.docker.com/pricing/resource-consumption-updates).

As a reminder, unauthenticated requests are limited to `100 per 6h`. Unauthenticated are IP-based and I believe part of our current problem is due to all `mwoffliner` workers being seen as the same IP by docker hub, thus virtually limiting this low limit by 5 ; so about an average of `3.3/worker/h`.

**Options**:
- Create user accounts for workers and authenticate pull requests. That will double the allowed requests (200/6h) and segregate them by worker.
- Limit further the number of pulls we make to run workers. Loosing too much flexibility to me, not a fan.
- Limit pulls by only publishing images with significant changes. Constraints on devel. Not a fan.
- [Run a registry ourselves](https://docs.docker.com/registry/). Would require some maintenance and scripts to auto-cleanup old images and the software does just the hosting.
- Subscribe to another registry service. Very few supports public repositories. We'd most likely need to authenticate our requests as in (1) and we'll have to add integration to it on github for all ZF images and all scrapers so there are built and hosted there as well.
  - [Docker hub](https://www.docker.com/pricing)
  - [Quay.io](https://quay.io/plans/)
  - [c8n.io](https://container-registry.com/#pricing)
  - [bintray](https://bintray.com/)
  - [treescale](https://treescale.com/)
  - [canister](https://www.canister.io/team)
  - [scaleway](https://www.scaleway.com/en/container-registry/)

**Comment by kelson42** [comment]
@rgaudin works on providing key Docker containers using Github Docker registery.

**Comment by kelson42** [comment]
This has been implemented for the most used images.

The Docker images are now built in Github actions and the uploaded on both Docker hub and Github actions.

We don’t have any impact anymore for the moment.

Scraper container which are still only on Docker hub will mpbe migrated as well, piece by oiece, in the next weeks and months.
