### ISSUE TITLE
“Hide offline workers” should last longer

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#588]
If I click on this button, it applies properly, ie. offline workers disappear.

Unfortunately after around a day, the offline workers reappear automatically.

It should not, as long as the button is not clicked again (to display offline workers).

I believe this is handled by a cookie which has an expiration time.... and it should not.

**Comment by kelson42** [comment]
@mahakporwal02 Would you volunteer to fix that one?

**Comment by mahakporwal02** [comment]
@kelson42 Sure
