### ISSUE TITLE
400 Bad request when trying to update recipe

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#598]
I cloned the existing [bibnum](https://farm.openzim.org/recipes/bibnum/edit) recipe on the farm which I renamed [culturegnum](https://farm.openzim.org/recipes/culturegnum/edit). Trying to change parameters (target website, description, file name) returns this error message upon saving:
`Error!
400: Bad Request
"Invalid Request JSON"
{"statsFilename":["Unknown field."]}.`

**Comment by rgaudin** [comment]
Thanks ; will fix and let you know
