### ISSUE TITLE
Farm returns 404 error eventhough the target site is up

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#602]
I've created this recipe for the [Fire Emblem wiki](https://fireemblemwiki.org/wiki/Main_Page) 

https://farm.openzim.org/recipes/fireemblem/edit

(the recipe was cloned from https://farm.openzim.org/recipes/europa_universalis_iv_en which works fine)

Surprisingly the first run returned a `404 error` even though the Fire Emblem site is up and running. I've then asked zimit to do a run... and it worked: https://farm.youzim.it/pipeline/093450a4ef42d7d0efb49006 

I realize this could be a mwoffliner issue as well, but not sure where's most appropriate.

**Comment by rgaudin** [comment]
You created an `mwoffliner` recipe ; for a mediawiki. Either the site is not a mediawiki or the recipe needs additional mwoffliner configuration.
