### ISSUE TITLE
gutenbergtozim DoS behavior with refused connections

### ISSUE THREAD

**Issue by kevinmcmurtrie** [openzim/zimfarm#607]
[//]: # (Pick appropriate classifiers)
- Location: Worker
- Schedule Name/ID: gutenberg_mul_all
- Task ID: 806bba557688d39ae7189206

## Problem
Scraper was rapidly hitting http://aleph.gutenberg.org while it was refusing TCP/IP connections.  This resembles a DoS attack and could result in clients being blacklisted.

https://farm.openzim.org/pipeline/806bba557688d39ae7189206/debug

## Reproducing steps
N/A.

**Comment by kevinmcmurtrie** [comment]
It happened again: https://farm.openzim.org/pipeline/97fbc40e1f235962f06ae206/debug

I disabled the gutenberg scraper on pixelmemory.

**Comment by kelson42** [comment]
> Scraper was rapidly hitting http://aleph.gutenberg.org while it was refusing TCP/IP connections.

What let you say the aleph.gutenberg.org refuses TCP/IP connections?
What let you believe this is a problem in the scraper?

**Comment by kevinmcmurtrie** [comment]
> > Scraper was rapidly hitting http://aleph.gutenberg.org while it was refusing TCP/IP connections.
> 
> What let you say the aleph.gutenberg.org refuses TCP/IP connections?

Over 1 million `Connecting to aleph.gutenberg.org (aleph.gutenberg.org)|65.50.255.20|:80... failed: Connection refused.`

> What let you believe this is a problem in the scraper? How should the scraper behave differently?

The scraper is retrying at an extremely high rate that is going to trigger automated denial-of-service detection.  1141028 connection attempts were made and refused in a short period of time.  Retries need to be throttled to a sane rate.
