### ISSUE TITLE
wikipedia_no_all flavours are generated but not listed

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#608]
As the title indicates, [wikipedia_no_all](https://farm.openzim.org/recipes/wikipedia_no_all) runs fine on the zim farm but cannot be found on [download](https://download.kiwix.org/zim/wikipedia/)

**Comment by kelson42** [comment]
@Popolechien which file is missing? You are confused because the files are called wikipedia_nb_... I guess.

**Comment by Popolechien** [comment]
Well OK but then the issue remains for no
![Screenshot_20210217_200230](https://user-images.githubusercontent.com/21675885/108254482-5bbce200-715b-11eb-9ca2-5fa2a7a95554.jpg)

**Comment by Popolechien** [comment]
Ah, looks like no redirects to nb for the online version...

**Comment by kelson42** [comment]
It is clear that it can not works properly because someone has forced the name in `wikipedia_no_top` recipe... wrongly!

**Comment by kelson42** [comment]
I have deleted the wrong name filenames `wikipedia_no_top*`, fixed the recipe, and relaunched a `wikipedia_no_top` recipe task.
