### ISSUE TITLE
Wikipedia_de_all fails to run with status code 413

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#620]
See here https://farm.openzim.org/recipes/wikipedia_de_all : the last two runs (April 8 and May 9) have both failed with the same error message

**Comment by kelson42** [comment]
Duplicate of https://github.com/openzim/mwoffliner/issues/1424

**Comment by rgaudin** [comment]
HTTP 413 is payload too large. You should move it to mwoffliner.
