### ISSUE TITLE
wikibooks_en_all_maxi redirect is not functioning

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#629]
wikibooks_en_all_maxi.zim (as listed on the wiki) should normally point to the last available zim file (https://mirror.download.kiwix.org/zim/wikibooks/wikibooks_en_all_maxi_2021-03.zim) but instead returns "unavailable". 

https://library.kiwix.org/wikibooks_en_all_maxi works on library.kiwix.org so I don't know if it also impacts the cardshop or not.

**Comment by rgaudin** [comment]
This has nothing to do with zimfarm. If there is a missing redirect for files on the server, that should be moved to maintenance repo.
