### ISSUE TITLE
Zimfarm auto-cancel and relaunch task weirdly

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#637]
I see a pattern which is more often these last days. Here an example:
![image](https://user-images.githubusercontent.com/1029718/129861784-f0ffa781-2e97-4b0c-ae8c-1911b8a70abd.png)

I wonder why this is cancelled and why this is restarted just afterward.

**Comment by kelson42** [comment]
The problem seems that the worker is not able to start the task properly/quickly enough. Here an other example where the worker failed to start the task within 30mn:
![image](https://user-images.githubusercontent.com/1029718/129871525-16fdc3ac-4fb6-464c-96d5-8b93a5e91c2c.png)

**Comment by rgaudin** [comment]
Yes, that's what I told you. Now either there is a pull issue or the worker crashes/freezes on startup.

**Comment by rgaudin** [comment]
Found the issue
