### ISSUE TITLE
Add support of Wikihow content

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#640]
Few things to do:
* Allow to upload to `zim/wikihow` directory on `download.kiwix.org`
* Add category `wikiHow`
* Add recipes for ALL languages of wikiHow

**Comment by rgaudin** [comment]
@kelson42 please make sure category is handled properly on other projects. I know that at least iOS has a hard-coded list of categories

**Comment by kelson42** [comment]
@rgaudin Actually this concerns only the one which have it hardcode, ie. iOS (macoOS) and Android. They should use the libkiwix feature to get the proper list of categories.

**Comment by rgaudin** [comment]
OK, so between now and *when you do use libkiwix*, you understand that wikihow ZIM will not appear in their libraries.

**Comment by kelson42** [comment]
@rgaudin see as well https://github.com/openzim/wikihow/issues/61, all the rest should come automatically.

**Comment by kelson42** [comment]
> OK, so between now and _when you do use libkiwix_, you understand that wikihow ZIM will not appear in their libraries.

This is an assumption, this is not always the case. But here we should focus on the Zimfarm.

**Comment by rgaudin** [comment]
> > OK, so between now and _when you do use libkiwix_, you understand that wikihow ZIM will not appear in their libraries.
> 
> This is an assumption, this is not always the case.

It's not an assumption for iOS; Remember TED ?

> But here we should focus on the Zimfarm.

I am making sure you understand the consequences before going this direction.

**Comment by kelson42** [comment]
I understand, but one problem at a time. First generate the proper ZIM files, at the right place and then make them available.

**Comment by rgaudin** [comment]
done
