### ISSUE TITLE
Allow more choices beetwen 16gb and 32gb of RAM

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#642]
It is no good to have to allocate 32gb if only 22gb is necessary

**Comment by rgaudin** [comment]
Are you talking about RAM resource ? Please suggest what you'd like:

- additional choices ? List them.
- Another kind of input ? We could have an integer field that is a number of GiB for instance. Drawback is sub-giga needs to be specified as decimal (`0.5`) which people find confusing.

**Comment by kelson42** [comment]
IMO just providing 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32 additional choices in the selectbox is the best thing to do.
