### ISSUE TITLE
Unable to upload SSH public key

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#644]
![image](https://user-images.githubusercontent.com/1029718/133571177-53fa5563-c79c-46f1-b342-09091c0c024b.png)

With following file:
[id_rsa.pub.txt](https://github.com/openzim/zimfarm/files/7175763/id_rsa.pub.txt)

**Comment by kelson42** [comment]
@mahakporwal02 Any idea what is going wrong here?

**Comment by rgaudin** [comment]
It has to be at most 2048b which at time of writing the doc was the default but is not anymore (3072)

**Comment by rgaudin** [comment]
Fixed the doc.
