### ISSUE TITLE
ZIM watcher keeps recreating a visible useless directory

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#649]
Today again at https://download.kiwix.org/zimfarm-watcher/... I guess this is at container start!

**Comment by rgaudin** [comment]
- this is part of the [maintenance config](https://github.com/kiwix/maintenance/blob/master/docker-compose.yml#L188)
- empty doesn't mean useless

Kinda concerned you kept on deleting a folder marked zimfarm without asking!

I'll let you change the compose to another path, not inside downloads/. This folder is used to download SO files to before uploading them to S3 (and then removing the local file)

**Comment by kelson42** [comment]
ok, then we should have it in /data/zimfarm-watcher.

**Comment by rgaudin** [comment]
> ok, then we should have it in /data/zimfarm-watcher.

Exactly what I proposed… Not a zimfarm ticket anymore…

**Comment by rgaudin** [comment]
Fixed https://github.com/kiwix/maintenance/commit/c19062e24a597ddbbcad2be5756002657ad7fd6d
