### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by AniruddhaChattopadhyay** [openzim/zimfarm#651]
There is a typo in the readme under How do I request a zim file header. The line is: If there's already a scraper for he website you want to convert to ZIM.... , I believe instead of he website it should be the website.
I am attaching the screenshot of the same. 
![image](https://user-images.githubusercontent.com/33848189/145335745-051434de-dcf5-4aaf-a2ec-8321dfc26b21.png)

**Comment by AniruddhaChattopadhyay** [comment]
I am new to open source contribution. Although this is a simple fix I would really appreciate it if you allow me to do it.

**Comment by kelson42** [comment]
@AniruddhaChattopadhyay yes, please go ahead
