### ISSUE TITLE
Recipe for wikipedia_en_medicine_app appears to have failed

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimfarm#657]
See  https://farm.openzim.org/pipeline/66e41594485241d457733b16 .

So I can't make a WikiMed for December because there is no `wikipedia_en_medicine-app_maxi_2021-12.zim` this month.

Can it be restarted?

**Comment by rgaudin** [comment]
@kelson42 can you relaunch and close ?

**Comment by kelson42** [comment]
Done
