### ISSUE TITLE
File not moved to library

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#658]
[canadian_prepper_surviving-disaster.zim](https://farm.openzim.org/recipes/canadian_prepper/edit) was completed two weeks ago yet cannot be seen on library.kiwix.org

**Comment by rgaudin** [comment]
Zimfarm has nothing to do with Library. Recipe asked worker to upload to /videos which it did. The script that builds the library.xml for library.kiwix.org is in maintenance repo.
