### ISSUE TITLE
Support dynamic worker IP

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#659]
Updated workers' README to include that we require a fixed public IP. Zimfarm itself doesn't need it but most our recipes now include S3 cache which works using an IP whitelist.

Interesting (in terms of resources) worker without a fixed public IP is probably rare but I think we've been offered this once and we're seeing it again so it's worth looking into what it would take to make it work.

As we can programmatically update the whitelist, we can imagine the zimfarm updating it based on some sort of event:

- we could compare a worker's IP during poll requests with what we have in store (we'd need to store IPs which we are not doing currently) and trigger if different.
- we could update the whitelist on worker registration. that would require the worker to register (`zimfarm restart`) after every IP change.

Option 1 is probably easier for worker owners as it doesn't require anything. It's important to note that any IP change during the polling interval (3mn by default) would not be captured and would result in failure to access the cache (consequences may differ based on the scraper) so it would still be recommended to attach a `zimfarm restart` to any re-connection/IP change.

**Comment by simonliu99** [comment]
Could be possible for the zimfarm manager to run a ddclient-like container that sends an update request whenever it detects an IP change. That way, the upstream servers don't have to do any additional checks as the IP change would be detected locally and then reported upstream.

**Comment by rgaudin** [comment]
I don't think it's helping much as:
- we don't want to trust worker on this as it would raise external connections so we'd still keep a record of IPs to prevent updates if there's no change.
- there isn't much of a *check* as we'd only look at the request's IP so this is transparent.

With this in mind, I don't see any advantage for this solution while it would introduce a lot of additional stuff.
