### ISSUE TITLE
Question: is there an api to monitor progress and success failure of a recipe?

### ISSUE THREAD

**Issue by tim-moody** [openzim/zimfarm#660]
I would like to automate a process that depends on successful completion of zim generation by the zim farm. Is there an api to poll the status?

**Comment by kelson42** [comment]
@tim-moody You should find what you search at https://api.farm.openzim.org/v1... but like I said at many occasion, the zimfarm is not a publishing tool. So you should assume that because a ZIM has been made it will be published.

**Comment by tim-moody** [comment]
@kelson42 I am less concerned about when a zim will get published than whether successful creation has occurred so that I can update the mdwiki cache without colliding with the creation process.

**Comment by rgaudin** [comment]
I believe the API is sufficient for your need. You can query the schedule for the `most_recent_task` and from the task you can check once the ZIM is created or not. This would be polling only though.

If you don't want to poll, we have a `zimfarm-events` channel on Slack that reports status of all tasks. This is linked to our notification system that supports webhook, slack an email but we have no UI at the moment. If that's something you'd be interested in, please weight in on #575
