### ISSUE TITLE
Remove dispatcher related images from docker hub

### ISSUE THREAD

**Issue by automactic** [openzim/zimfarm#67]
All dispatcher related images should be removed form docker hub, as no one is / will be using them

**Comment by kelson42** [comment]
@chris Still doubting this is the best path. Need a bit more time to figure out.

**Comment by automactic** [comment]
@kelson42 I still think we should remove those images. They are not used by anyone.

**Comment by kelson42** [comment]
@automactic I have removed all zimfarm related images except the warehouse and worker. Making docker stuff without image repository is bad practice. That said, I understand that in our case, for the zimfarm central node, it does not make a bit difference. One time we will move all of this to a proper cloud, we will have to recreate them.

**Comment by automactic** [comment]
> a proper cloud

lol How would we define a proper cloud? The current host is not a proper cloud?

I still don't think we would ever have to recreate those containers. We are not *distributing* the containers that collectively becomes the central node as a software solution.

Anyway, discussion for another day and time...

**Comment by kelson42** [comment]
@automactic with proper cloud, I mean a docker specialized cloud, like we use for most the other services we have. This would be BTW meanwhile possible. We will looks at this later.
