### ISSUE TITLE
Include Dagbani (dag) in language list

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#677]
[Dagbani Wikipedia](https://dag.wikipedia.org/) has left the incubator and is now a standalone wiki. Language ISO code is `dag`.
I've [created the recipe](https://farm.openzim.org/recipes/wikipedia_dag_all/edit) already but not run it yet.

Is there any other place where I should flag this new language (e.g. reader UI or something)?

**Comment by rgaudin** [comment]
Fixed. I don't think readers need anything
