### ISSUE TITLE
Introduce support of iFixit scraper

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#687]
So we can run it in the zimfarm

**Comment by kelson42** [comment]
Ping @benoit74

**Comment by benoit74** [comment]
Command line is quite in line with wikihow. I would advise to start with `ifixit2zim --language fr --output /whatever --optimization-cache $MYURL --tmp-dir /tmp --max-missing-items-percent 100 --max-error-items-percent 100`
The two last parameters are useful to ensure the scraper does not stop even if errors or missing items are encountered. Shouldn't happen anyway, so feel free to not use them.

Available languages might be found here : https://github.com/openzim/ifixit/blob/200f464bb7353c686ff08b7cea7da910468a6f90/ifixit2zim/constants.py#L22

**Comment by kelson42** [comment]
And make one recipe for each of these languages: en, fr, pt, de, ru, ko, zh, nl, ja, tr, es, it. I would make only one ZIM per recipe (with pictures and videos).
