### ISSUE TITLE
ZIMs aren't getting transferred correctly to download.kiwix.org

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimfarm#688]
I know this was a problem with the latest full English ZIM, but I'm seeing it also with Wikivoyage, which is a much smaller file of course: https://farm.openzim.org/pipeline/1c191e4b2815420b92f96526 . File is not available on download.kiwix.org despite it being given a mirror link (which returns 404).

I'm aware this is a known issue, but I couldn't find an issue on here to post it to. Possibly #684 ?

**Comment by kelson42** [comment]
I got a report from a user about https://farm.openzim.org/pipeline/7202524c1e0593dd4e119326 as well.

**Comment by kelson42** [comment]
@rgaudin Not sure all these problem have the same rootcause, but this starts indeed to be a bit worrying.

**Comment by rgaudin** [comment]
Regarding the wikivoyage one, the wikivoyage folder was missing on the receiver. Not sure how it got missed in the migration. ✅ Fixed. I've also triple-checked that we have them all now.

```
tree -a zim/
zim/
├── gutenberg
├── .hidden
│   ├── bard
│   ├── custom_apps
│   ├── dev
│   ├── endless
│   └── private
├── mooc
├── other
├── phet
├── psiram
├── stack_exchange
├── ted
├── videos
├── vikidia
├── wikibooks
├── wikihow
├── wikinews
├── wikipedia
├── wikiquote
├── wikisource
├── wikiversity
├── wikivoyage
├── wiktionary
└── zimit
```

Regarding the crashcourse one, it's an old task that was created in march and which had the former upload URI.

**Comment by Jaifroid** [comment]
OK, thanks for the update!

**Comment by kelson42** [comment]
@Jaifroid I have relaunched the Wikivoyage task
