### ISSUE TITLE
Sotoki template generates wrong command

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#691]
At https://farm.openzim.org/pipeline/cee0f5ee4634b3875af8f626/debug

usage: sotoki [-h] -d DOMAIN [-l] [--name NAME] [--title TITLE]               [--description DESCRIPTION] [--favicon FAVICON]               [--creator AUTHOR] [-p PUBLISHER] [--tag TAG] [--without-images]               [--without-user-profiles] [--without-user-identicons]               [--without-external-links] [--without-unanswered]               [--without-users-links] [--without-names]               [--censor-words-list CENSOR_WORDS_LIST] [--output _OUTPUT_DIR]               [--threads NB_THREADS] [--tmp-dir _TMP_DIR] [--zim-file FNAME]               [--optimization-cache S3_URL_WITH_CREDENTIALS] [--mirror MIRROR]               [--redis-url _REDIS_URL] [--debug]               [--stats-filename STATS_FILENAME] [--prepare-only] [--keep]               [--keep-redis] [--keep-intermediates] [--build-in-tmp]               [--defrag-redis DEFRAG_REDIS] [--shell] [--dev-skip-tags-meta]               [--dev-skip-questions-meta] [--dev-skip-users] [--version] sotoki: error: unrecognized arguments: --no-userprofile --no-identicons
--

**Comment by kelson42** [comment]
Once fixed, IMO this recipe shoukd be deleted

**Comment by rgaudin** [comment]
There are no such thing as zimfarm templates but that incorrect (option name changed) `--no-userprofile` was present in 3 other recipes. Fixed them all and delete that (test probably) recipe.

**Comment by kelson42** [comment]
@rgaudin Hope you did as well --no-identicons

**Comment by rgaudin** [comment]
It was the only one using it
