### ISSUE TITLE
Add plateform limit for ifixit scraper

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#696]
Allowing only one scrape at the same time. There is no complain so far on their side, but would prefer to act earlier than later.

**Comment by kelson42** [comment]
We got our first HTTP 429 https://farm.openzim.org/pipeline/820297f4628efdffcbce8926/debug

**Comment by kelson42** [comment]
@rgaudin Any chance we could have this ticket implemented next week?

**Comment by rgaudin** [comment]
Done.

**Comment by rgaudin** [comment]
Eventually fixed.
