### ISSUE TITLE
Youtube API keys seem to be invalid/outdated

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#700]
It seems we use invalid (outdated?) Youtube API keys, see:
* https://farm.openzim.org/pipeline/b36721ff34d7c74878d62a26/debug
* https://farm.openzim.org/pipeline/41aea85f88c19df29a8a1a26/debug
* https://farm.openzim.org/pipeline/effa0b23e7a41c32a7c73926/debug

**Comment by rgaudin** [comment]
The log says 

```json
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_IP_ADDRESS_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/478677497152",
          "service": "youtube.googleapis.com"
        }
      }
```

You know YT API Keys are protected by an IP whitelist that's static and different from the dynamic one we have for Wasabi. Maybe pixelmemory's public IP changed or is using IPv6 now. We have `99.xx.xxx.75` ATM.

**Comment by rgaudin** [comment]
I'll add the v6 prefix ; thanks

**Comment by rgaudin** [comment]
Done ; thank you

**Comment by kevinmcmurtrie** [comment]
There are a lot of problems with Docker's bridge network and its image management.  I was hoping that IPv6 could bypass some problems but it created more.  At this point I don't know what's needed to make it reliable and whether or not those changes could be compatible with the way Zimfarm launches its own containers.

- Docker's bridge network triggers a race condition in Linux SNAT that results in random connection failures.  This is a well known bug.  A partial workaround is to replace one of Docker's iptables rules after Docker starts up.
- There's a known but unlocated bug where IPv4 routing temporarily breaks between one container and one host.  Pixelmemory is hitting this frequently after software updates.  Nobody knows what causes it so there's no workaround other than fussing with random things until it goes away.
- Docker has been claiming to support IPv6 for years but it's chronically broken in both documentation and implementation.  Docker can finally declare its own iptables rules to make IPv6 work but they're incorrect.
- Docker has race conditions managing storage layers that result in deadlocks and I/O errors.  This hits my day job frequently but it has corrupted Pixelmemory a couple of times too.  It's especially nasty to clean up with the ZFS storage driver.

**Comment by kevinmcmurtrie** [comment]
At least IPv6 is working now without NAT.  Manual testing works but there's no applicable tasks in the pipeline for me to  monitor.

```
docker run -it bigubuntu

root@e3b99777976c:/# echo $(curl -s v6.ident.me) "     " $(curl -s v4.ident.me)
2600:1700:2320:9090:d0cc:242:ac11:3       99.87.255.76

root@e3b99777976c:/# ifconfig eth0 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.3  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:acff:fe11:3  prefixlen 64  scopeid 0x20<link>
        inet6 2600:1700:2320:9090:d0cc:242:ac11:3  prefixlen 80  scopeid 0x0<global>
        ether 02:42:ac:11:00:03  txqueuelen 0  (Ethernet)
        RX packets 263  bytes 37693 (37.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 291  bytes 29260 (29.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
I don't know if the Docker bridge stalling is fixed at all.
