### ISSUE TITLE
docker.errors.ImageNotFound errors on pixelmemory worker

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#702]
A few example of recently failing tasks:
* [pixelmemory] https://farm.openzim.org/pipeline/33212e41336968671c010a26/debug
* [pixelmemory] https://farm.openzim.org/pipeline/91cb14ce0951642b5ce10a26/debug
* [pixelmemory] https://farm.openzim.org/pipeline/29ed6af99c6f34c20fa30a26/debug
* [pixelmemory] https://farm.openzim.org/pipeline/f503def3cc513cd701940a26/debug
* [pixelmemory] https://farm.openzim.org/pipeline/d4c1a725ef45e94a82750a26/debug
* [pixelmemory] https://farm.openzim.org/pipeline/00f2920516c3b7c0597c0a26/debug
* [pixelmemory] https://farm.openzim.org/pipeline/8b467481f6726dca3a5d0a26/debug

At this stage, I have stopped to try to find other cases... it seems to be a pixelmemory specific error.

**Comment by rgaudin** [comment]
Looks like pixelmemory admin has incorrectly configured a custom image to use

```
No such image: pixelmemory/notcache:latest
```

**Comment by kevinmcmurtrie** [comment]
This is the DNS image but without the TTL extension. I had accidentally purged it 🤦‍♂️ doing Docker cleanup.  I didn't notice for a while because there was nothing in the pipeline while I was watching it.

**Comment by kelson42** [comment]
@kevinmcmurtrie Does the problem is fixed? Should we close the ticket?

**Comment by kevinmcmurtrie** [comment]
It should have only been broken for a few hours, nothing more.  I can turn the worker off if the failure rate is still high.

**Comment by kelson42** [comment]
Ok, then I will close and reopen if necessary.
