### ISSUE TITLE
Enable basic html formatting in content descriptor

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#719]
(not sure if this is a zimfarm or kiwix-server option)
Some of our zim files have fairly long descriptions and we end up with a block of text. It would be convenient if in the `Description` field of recipes we could insert some basic HTML (e.g. `<br/>`) so as to render this text in a more palatable format 
![Capture d’écran 2022-09-23 à 14 41 09](https://user-images.githubusercontent.com/21675885/191962435-a6ea9fba-6239-4d3b-90e4-88c6c1eaf5c1.png)

**Comment by rgaudin** [comment]
As per [the spec](https://wiki.openzim.org/wiki/Metadata) `Description` is `description of content (one short sentence)` so the answer is no. I am closing this as there is no foreseeable solution at zimfarm level now but feel free to open a discussion at openzim/overview or libzim about that
