### ISSUE TITLE
Upload fails due to unprotected private key file

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zimfarm#721]
I don't know if this is a one-off error, but while investigating the apparent failure to upload the latest scrape of `wikivoyage_en`, I found a strange error (see below) in the [debug log](https://farm.openzim.org/pipeline/39db5ae82f591d1f5a56b436/debug). It looks like bad permissions for `/etc/ssh/keys/zimfarm`, possibly on one runner?

Would it be possible to fix and re-run, as I'm waiting for this ZIM to release the latest Wikivoyage packaged Electron/UWP apps?

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/etc/ssh/keys/zimfarm' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/etc/ssh/keys/zimfarm": bad permissions
uploader@warehouse.farm.openzim.org: Permission denied (publickey).

Connection closed.  
Connection closed

[2022-10-16 03:32:05,890: ERROR] wikivoyage_en_all_maxi_2022-10.zim exhausted retries (5)
[2022-10-16 03:32:05,890: INFO] Updating file-status=failed for wikivoyage_en_all_maxi_2022-10.zim
```

**Comment by kelson42** [comment]
@Jaifroid The ZIM files seem uploaded!? What ZIM file has not been uploaded?

**Comment by Jaifroid** [comment]
I'm looking for `wikivoyage_en_all_maxi_2022-10.zim` and I'm getting 404 not found on both download.kiwix.org and mirror.download.kiwix.org, e.g. https://mirror.download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_maxi_2022-10.zim.

**Comment by kelson42** [comment]
Indeed

**Comment by rgaudin** [comment]
Wow ; thanks for the report. This was preventing upload indeed. There was an issue on mwoffliner4 the other day and I accidentally removed the private key… but put it back… incorrectly.
I fixed the permissions and tested a small run that uploaded correctly.

**Comment by Jaifroid** [comment]
Great, thanks! If, in due course, someone could restart [wikivoyage_en](https://farm.openzim.org/pipeline/39db5ae82f591d1f5a56b436), that would be brilliant, so that I can release a new Wikivoyage packaged app later this week.

**Comment by rgaudin** [comment]
Restarted!
