### ISSUE TITLE
Redirect HTTP -> HTTPS

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#73]
Would be nice if http://farm.openzim.org/ redirects to https://farm.openzim.org/. Your Nginx reverse proxy can do that easily, it is just a configuration stuff.

**Comment by automactic** [comment]
I tested on safari and Firefox. It already does the redirection. No fix is needed.

@kelson42 Could you please test if the redirection happens for you.

**Comment by kelson42** [comment]
@automactic

Works fine now:
```
$ curl -I http://farm.openzim.org
HTTP/1.1 301 Moved Permanently
Server: nginx/1.15.6
Date: Wed, 26 Dec 2018 12:17:06 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
Location: https://farm.openzim.org/
```
