### ISSUE TITLE
zim files fail to move to library

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#730]
The following recipes were created and apparently completed, but the resulting zim files can be seen neither in dev.library.kiwix.org nor in library.kiwix.org

- https://farm.openzim.org/recipes/feed_the_beast_wiki
- https://farm.openzim.org/recipes/rapsberry_pi_docs
- https://farm.openzim.org/recipes/openstreet_map
- https://farm.openzim.org/recipes/core_knowledge
- https://farm.openzim.org/recipes/practical_action

**Comment by rgaudin** [comment]
Yep, they all suffer from this. Recipes must be fixed.
