### ISSUE TITLE
Dumps for lurkmore_ru

### ISSUE THREAD

**Issue by 1over137** [openzim/zimfarm#736]
Sorry if this is not the right place to report this. The site lurkmore.to was taken down in February 2022. I see a job for it but the earliest shown job was in April. I also can't find a copy of the zim file on downloads.kiwix.org. Has a valid scrape ever been created for this website? If so, where may I be able to get a hold of the file? Or has this never been done successfully before?

**Comment by Popolechien** [comment]
@1over137 There have been [several requests](../../zim-requests/issues?q=is%3Aissue+lurkmore+is%3Aclosed) over time for lurkmore in the past - I checked and we never got it to work, so unfortunately that one will be a loss for ever :-(
