### ISSUE TITLE
Identify easily completed transfered file in warehouse

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#74]
ZIM files from the warehouse will be checked (for integrity) and transfered to their final place to be available at http://download.kiwix.org. But, to do that properly, the system needs to know if a file has been properly transfered, ie. completed.

**Comment by kelson42** [comment]
An idea how to solve the problem: I propose to transfer all file with a temporary name, for example by adding `.tmp` at the end, and afterward, **if the transfer has be OK (the FTP server tells the FTP client)** then the client will ask to rename the file, ie. remove the `.tmp` suffix.

**Comment by automactic** [comment]
I have implemented this above logic on the worker side in #88. 

However, warehouse currently does not allow file rename. So a new warehouse image is supposed to be deployed.

**Comment by automactic** [comment]
Implementation finished. I recommend wait for https://github.com/openzim/mwoffliner/issues/496 to be resolved for some further testing

**Comment by kelson42** [comment]
OK. I'll assume it works and reopen the ticket if not.
