### ISSUE TITLE
Rollout MWoffliner 1.12.0

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#743]
[MWoffliner 1.12.0 has just been released](https://github.com/openzim/mwoffliner/releases/tag/v1.12.0).

This new version of MWoffliner has a few changes in its call API:
* Remove "Use Zstandard compression" and clean the recipes/tasks (it will always be using zstd anyway).
* Remove "Don't fallback to local Parser" and clean the recipes/tasks (actually has already been deprecated in `1.11.12`)
* Add `--articleListToIgnore`, expect same format like `--articleList`
* Add `--longDescription`, expect a long description (maybe put a `textarea`

Please update all the recipes to this new version (of the Docker image). Remove also verbose everywhere if configured for MWoffliner.

**Comment by rgaudin** [comment]
Note that the option not to fallback on local parser was not used at all

**Comment by kelson42** [comment]
@rgaudin Thx!
