### ISSUE TITLE
Add guw (gungbe) to list of available languages

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#744]
See for instance guw.wikipedia.org which has recently been released from incubator.

**Comment by rgaudin** [comment]
There is no static list of languages in zimfarm. You need to create a recipe (with incorrect language) and post it here with the new ISO-639-3 code and I'll fix it (in the DB). It will then be in the select list.

**Comment by Popolechien** [comment]
Created
https://farm.openzim.org/recipes/wikipedia_pcm_all
https://farm.openzim.org/recipes/wikipedia_guw_all
https://farm.openzim.org/recipes/wikiquote_guw_all
https://farm.openzim.org/recipes/wiktionary_guw_all

**Comment by rgaudin** [comment]
Change the first two ; now those are in the list, you can fix the other two yourself.

For the record, those recipe names look incorrect (using ISO-639-3 codes) but they are not: those two languages don't have ISO-639-1 codes. I'm not sure what filenames will be produced by mwoffliner though…

**Comment by Popolechien** [comment]
Done, thanks. @rgaudin will this be implemented in library.kiwix.org or should I open a ticket at libkiwix or somewhere else too?

**Comment by rgaudin** [comment]
This language setting only affects zimfarm UI. It's not tied to the ZIM `Language` metadata which for mwoffliner is nt provided (retrieved from the wiki's API).

kiwix-serve language filter selector automatically include languages for which it has content so there's nothing else to do.
