### ISSUE TITLE
Last lines of logs not always visible

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#751]
Time to time it is completly empty:
https://farm.openzim.org/pipeline/db9780f7906bf967aa6fbd36/debug

**Comment by rgaudin** [comment]
It's not. The last hundred lines of log from this scrape all start with a ton of `\t` with a number at the end.
Just scroll to the right and you'll see it. Or use the copy button and paste it to your text editor.

You can also use the download log button to get the earlier messages and understand why the last ones are this way.
