### ISSUE TITLE
Lots of "504 gateway timeout errors" in task worker log

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#752]
https://farm.openzim.org/pipeline/58fdbca6a3bc0af439ea8046/debug

**Comment by rgaudin** [comment]
Interesting…

**Comment by rgaudin** [comment]
Thanks for the report ; it was not the zimfarm returning 504 but the CMS, when called to create a Book for the successfully checked ZIM. The trace prints what the CMS returned to the zimfarm API.

The issue seemed to be with concurrent connection use. I've updated the DB stack we use on the CMS but there are several inter-dependency constraints and I've also set the size of the connections pool from 10 (default) to 20.
We'll see if this is enough. We plan anyway to change part of that stack and improve performance so this should be somewhat temporary anyway.

Note that it didn't affect the zimfarm as this call purposely happens after the event processing in the farm and failed calls to CMS are retried periodically
