### ISSUE TITLE
Remove `last_used` column in ssh keys and remove `POST /auth/validate/ssh_keys` endpoint

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#761]
In the database, ssh keys have a `last_used` property.
The property is updated only when the `POST /auth/validate/ssh_keys` endpoint is used, not others.
The property should also be updated with the `POST /auth/ssh_authorize` endpoint (and maybe others, tbc).

**Comment by benoit74** [comment]
This is even weirder than expected: the `POST /auth/validate/ssh_keys` is not working anymore since the migration to PostgreSQL, the `@dbsession` annotation was missing.

I tried to create a test to exercise this endpoint but failed ; code is on the [fix_ssh_validate branch](https://github.com/openzim/zimfarm/tree/fix_ssh_validate)

In any case, this raises two questions:
- should we keep this code/endpoint if it is dead/not used anymore?
- should we keep this `last_used` property if it is not updated on the regular `POST /auth/ssh_authorize` endpoint and only updated on a dead one?

**Comment by rgaudin** [comment]
Good catch

> should we keep this code/endpoint if it is dead/not used anymore?

No. It seemed to be from Chris's code and was apparently never used. I thought maybe the receiver used it but no, it uses a different and better suited endpoint. I'm in favor or removing all together.

> should we keep this last_used property if it is not updated on the regular POST /auth/ssh_authorize endpoint and only updated on a dead one?

No, we're not using and I don't see us using it. Should the need arise, we can bring it back (or differently).
