### ISSUE TITLE
xml2js is vulnerable to prototype pollution

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#762]
See https://github.com/openzim/zimfarm/security/dependabot/125

**Comment by rgaudin** [comment]
We don't use `xml2js` and it doesn't appear in dependencies either (no trace in `package.json` nor `yarn.lock`)

**Comment by rgaudin** [comment]
It's a dependabot bug. It seems to have cached a long-gone `dispatcher/frontend/package-lock.json` file
