### ISSUE TITLE
Allow disabling users and workers

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#763]
For archive reason, we don't want to ever delete user accounts as those can be linked to data that is still valuable.
Should a user not be allowed to authenticate anymore, we should be able to _disable_ it.

Same goes for Workers which are versatile by nature. We should be able to mark them disabled and keep them in the database.

Shall be implemented along #317 

**Note**: this ticket is only about technical capability (database column), not about UI to handle those capabilities

**Comment by benoit74** [comment]
What I propose (PR to come):
- add a `deleted` column in DB for worker + user
- when someone deletes a user (from the UI / API), the user is not deleted anymore, it is just marked as "deleted"
- the workers cannot be deleted from the UI / API, this must be done from the DB
- there is no undelete from the UI / API, this must be done from the DB

When a worker is deleted :
- it is not shown anymore in the list of workers in the UI
- it is still visible in tasks that have been ran by this worker
- its durations are kept and visible

When a user is deleted :
- all its workers have the same behavior as above (but they are not marked as deleted in the DB, just the API / UI behaves the same)
- it is not capable to login anymore (no password, no refresh token, no SSH key)
- it is not shown anymore in the list of users in the UI
- it cannot be modified anymore (email, password, SSH keys, ...)

**Comment by rgaudin** [comment]
Good ; let's do this
