### ISSUE TITLE
File fails to upload to /.hidden/dev

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#765]
The fipeco run completed about [21 hours ago](https://farm.openzim.org/pipeline/13a645b485d49f029775e346) but the file can't be seen on dev.library.kiwix.org (the currently available one is from last year).

**Comment by rgaudin** [comment]
Upload is different than being in the library. File was properly uploaded. Your link has a link to it that works.

Checking why the dev library failed to gen

**Comment by rgaudin** [comment]
Ah it's due to the FCC test ZIM that I manually uploaded for you to look-at. It wasn't respecting the filename convention. Fixed.
