### ISSUE TITLE
504 errors on zimcheck logs upload

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#767]
In this [gutenberg task](https://farm.openzim.org/pipeline/64d2c2a62c45ca437da64346/debug), I see many 504 errors trying to send the zimcheck status. Looks like it starts with a 413 (probably due to large size of zimcheck log) then we see the 504.

Might be to to our mongo instance lacking resources??

**Comment by benoit74** [comment]
No repro, even with gutenberg, should we close this one?

**Comment by rgaudin** [comment]
Definitely
