### ISSUE TITLE
Clarify that Title should be max 30 characters long

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#777]
Creating a zim file whose title is longer than 30 characters will cause the job to crash. This should either be explicitely indicated in the `Title` field (with a small counter to indicate where one is) or if there is no particular reason for this limit then extend to something along the lines of 60 characters.

**Comment by rgaudin** [comment]
The limit is a _recommendation_ of the [spec](https://wiki.openzim.org/wiki/Metadata). See [log](https://wiki.openzim.org/w/index.php?title=Metadata&diff=31251&oldid=31246).

We've decided to enforce our own recommendation at scraperlib's level.

What's left is:

- Update zimfarm to enforce limits at ZF edition level
- Update the descriptions to indicate the limits.
- discuss whether there are valid cases –for us– to allow longer Titles.
- If so, extend scraperlib and the scrapers in question to support it

**Comment by Popolechien** [comment]
> Update zimfarm to enforce limits at ZF edition level

This would probably be the most efficient

**Comment by rgaudin** [comment]
As explained in another ticket ; we'd still need to discuss and adapt the scrapers that uses dynamic metadata: YT, TED for instance

**Comment by kelson42** [comment]
@rgaudin 

> As explained in another ticket ; we'd still need to discuss and adapt the scrapers that uses dynamic metadata: YT, TED for instance

AFAIK this part has been achieved meanwhile. @benoit74 you conform, otherwise can you please list the blocking issues?

**Comment by benoit74** [comment]
Now TED and Youtube are not creating anymore ZIMs with titles longer than 30 characters, this is true, and this is correct that it should be reflected in the Zimfarm configuration. 

We probably have other scrapers in the same situation, to be checked when this issue will be implemented.

I propose to move this to prio1

**Comment by benoit74** [comment]
(it is already prio1, sorry ^^)

**Comment by benoit74** [comment]
Removed from zimit2 project unfortunately

**Comment by benoit74** [comment]
I've moved the part around displaying current number of characters used in https://github.com/openzim/zimfarm/issues/1025
