### ISSUE TITLE
Add "Tyap" language to the language list

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#785]
There is a new Wikipedia (request) in this language. See https://github.com/openzim/zim-requests/issues/654

**Comment by rgaudin** [comment]
Recipe must be created with a different language (it is only used within ZF, for filtering).

Then you give the ISO-639-3 code here and I'll update the recipe.

**Comment by kelson42** [comment]
Done at https://farm.openzim.org/recipes/wikipedia_kcg_all

**Comment by rgaudin** [comment]
Done
