### ISSUE TITLE
Two times "Azerbaijani" in the recipe language list

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#787]
Azerbaijani language can be represented in three manners:
* Azerbaijani macrolanguage with `az` and `aze` codes (represents the two following)
* Azerbaijani (latin script) with `azj`code
* Azerbaijani (arabic script) with `azb` code 

Whatever we do (1 entry or 2 entries), we should respect this.

FYI Wikipedia has two Wikipedias in Azerbaijani: `az.wikipedia.org` and `azb.wikipedia.org`

![image](https://github.com/openzim/zimfarm/assets/1029718/9881e30a-7b55-49d3-9913-24864fcd45ca)

**Comment by rgaudin** [comment]
I've set all of them to `az` because there were only two in `azb` and none of this really matters from ZF point of view (as long as recipes are correct).
