### ISSUE TITLE
Add new languages for recently-created Wikipedias

### ISSUE THREAD

**Issue by amire80** [openzim/zimfarm#789]
In recent years, several Wikipedias were created in new languages. Here's a list:
| Code on Wikipedia | Three-letter code | English name     | Native name      | Comment                                        |
|-------------------|-------------------|------------------|------------------|------------------------------------------------|
| alt               | alt               | Altay            | алтай тил        |                                                |
| ami               | ami               | Amis             | Pangcah          |                                                |
| anp               | anp               | Angika           | अंगिका            |                                                |
| ary               | ary               | Moroccan Arabic  | الدارجة          | Right to left                                  |
| avk               | avk               | Kotava           | Kotava           |                                                |
| awa               | awa               | Awadhi           | अवधी             |                                                |
| blk               | blk               | Pa'O             | ပအိုဝ်ႏဘာႏသာႏ      |                                                |
| fat               | fat               | Fante            | Mfantse          |                                                |
| gcr               | gcr               | Guyanese Creyol  | kriyòl gwiyannen |                                                |
| guc               | guc               | Wayuu            | wayuunaiki       |                                                |
| gur               | gur               | Farefare         | Farefare         |                                                |
| hyw               | hyw               | Western Armenian | Արեւմտահայերէն   |                                                |
| kcg               | kcg               | Tyap             | Tyap             |                                                |
| lld               | lld               | Ladin            | Ladin            |                                                |
| mad               | mad               | Madurese         | Madhurâ          |                                                |
| mni               | mni               | Manipuri         | ꯃꯤꯇꯩ ꯂꯣꯟ         |                                                |
| nia               | nia               | Nias             | Li Niha          |                                                |
| nqo               | nqo               | N'Ko             | ߒߞߏ              | Right to left                                  |
| pwn               | pwn               | Paiwan           | pinayuanan       |                                                |
| rn                | run               | Rundi            | Ikirundi         | Existed long ago, but isn't available on Kiwix |
| shi               | shi               | Shilha           | Taclḥit          |                                                |
| shy               | shy               | Shawiya          | tacawit          |                                                |
| skr               | skr               | Saraiki          | سرائیکی          | Right to left                                  |
| smn               | smn               | Inari Sami       | anarâškielâ      |                                                |
| szy               | szy               | Sakizaya         | Sakizaya         |                                                |
| tay               | tay               | Atayal           | Tayal            |                                                |
| trv               | trv               | Seediq           | Seediq           |                                                |

Adding these languages will allow creating recipes and adding scraping configuration for them.

**Comment by kelson42** [comment]
Depends on https://github.com/openzim/zim-requests/issues/655

**Comment by rgaudin** [comment]
Fixed
