### ISSUE TITLE
Task history not sorted

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#794]
https://farm.openzim.org/recipes/mitopencourse_en_all

The task on top was started on May 23rd while the second one was started on May 25th.
Those tasks should be sorted with latest on top.

I believe we don't do anything on the client about that so the order must have changed on the API response.

**Comment by benoit74** [comment]
Ordering is done by time of last update, just like it was before :
Now : https://github.com/openzim/zimfarm/blob/1e3ab1e14cbe3ee59dd93bf01771046e0ec97c8a/dispatcher/backend/src/routes/tasks/task.py#L68
Before migrating : https://github.com/openzim/zimfarm/blob/ac18dd3738e0d386f80c52c10979319776746dc6/dispatcher/backend/src/routes/tasks/task.py#L66

**Comment by rgaudin** [comment]
OK makes sense.
