### ISSUE TITLE
Cancel-requester not shown

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#814]
In https://github.com/openzim/zimit/issues/210 a couple tasks are mentioned which were apparently canceled (at least one of them) by @benoit74 but none display a cancel-requester (neithrr in UI nor API).
Either we are not reporting that information back to API or we're not recording it anymore

**Comment by benoit74** [comment]
+1, I cancelled both tasks but we do not see I'm the "culprit" 🤣
