### ISSUE TITLE
Show recipe `enable` status in recipe list

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#816]
Currently, it is very hard to know that a recipe is disabled from automatic scheduling in the recipe list while it is quite an important information from my point of view.

I suggest we add an orange "pause" icon next to paused recipes names.

![image](https://github.com/openzim/zimfarm/assets/7102089/28b412f5-fd25-45bf-ad93-437ec90d1890)

**Comment by rgaudin** [comment]
Makes sense 👍

**Comment by gpuligundla** [comment]
HI @benoit74, can I work on this issue?

**Comment by benoit74** [comment]
Sure, contributions are always welcomed. 
Please pay attention to https://github.com/openzim/zimfarm/blob/main/CONTRIBUTING.md and https://github.com/openzim/overview/wiki/openZIM-workflow

**Comment by gpuligundla** [comment]
Hi @benoit74, I'm having difficulty loading prod backup data into the container to test the changes. 
Could you please help me?

**Comment by benoit74** [comment]
@gpuligundla Sure, could you be more specific about the problem you face? What has you already setup on your machine? Which procedure are you following? Do you get an error? At which point of the procedure?

**Comment by gpuligundla** [comment]
I have a dev docker setup on my machine. I want to load schedules backup data into the Postgres db container to do testing.

**Comment by benoit74** [comment]
Perfect! Why don't you load these schedules backup?

**Comment by rgaudin** [comment]
@benoit74 the backup is a JSON export and there is no import script for this into the DB.

**Comment by benoit74** [comment]
@rgaudin there are instructions here: https://github.com/openzim/zimfarm/blob/main/CONTRIBUTING.md#import-schedules-backup and an import Jupyter notebook here: https://github.com/openzim/zimfarm/blob/main/dev/import_schedules.ipynb

I already pointed the first documentation which explains that the Jupyter notebook is available for backup restore, and this is why I'm asking for more information about what "does not work" or "is blocking".

**Comment by rgaudin** [comment]
Ah I didn't see your comment 👍

**Comment by gpuligundla** [comment]
Ah, sorry, I didn't see the script!
Thank you
