### ISSUE TITLE
zimit offliner should validate Description length

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimfarm#828]
Description length is not checked/validated in zimit offliner. As this feed youzim.it, it allows users to input incorrect descriptions which fails the process pretty late.

https://github.com/openzim/zimfarm/blob/3c5a520269827a92eb1b90d6d639242c2dd18470/dispatcher/backend/src/common/schemas/offliners/zimit.py#L167-L170

**Comment by benoit74** [comment]
Oh sorry, I did not realized this was in the zimfarm repo. Got it. My other remarks where for zimit itself.

**Comment by benoit74** [comment]
I had a look at offliners definitions and the `/offliner` endpoint.

Offliners definitions are based on marshmallow and the only way to limit a field length is via the use of a validator (e.g. the [Length](https://marshmallow.readthedocs.io/en/stable/marshmallow.validate.html#marshmallow.validate.Length) validator provided by marshmallow). In other words, there is no field property to control this.

For many offliners, we used the `validate_zim_description` and `validate_zim_longdescription` validators, this is clearly missing for zimit and few others, I will do a PR for this.

However, I did not find any information returned in the offliner endpoint regarding validation logic, so I don't get how you expect this change to feed youzimit UI? 

I mean, I will add the `validate_zim_description` and `validate_zim_longdescription` operations to all offliners, this would avoid the creation of an invalid schedule on zimfarm side (which is already a great step forward), the error will be displayed on youzimit UI, but this won't "feed" youzimit UI as far as I can tell (or I didn't get what you meant by "feed").

**Comment by rgaudin** [comment]
youzim.it UI uses the Zimfarm offliner so you only need to add it to zimfarm and it will directly apply to youzim.it.
Of course, as we rely on server-side validation, it only prevent creating the task but isn't very user friendly. Still a lot better than current situation.
We could easily (separately) handle it via some custom metadata though that would set `minLength`/`maxLength` or even `pattern` of the HTML5 elements.

**Comment by benoit74** [comment]
OK, then we both have the same understanding.

**Comment by benoit74** [comment]
Issue opened: https://github.com/openzim/zimfarm/issues/835
