### ISSUE TITLE
HTTP HEAD verb is raising 500 errors

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#838]
It looks like all HTTP HEAD operations on implemented endpoints are returning an HTTP 500 error. 

This is returning an HTTP 500:
```
curl -I 'http://localhost:8000/v1/schedules/?skip=0&limit=10'
curl -I 'http://localhost:8000/v1/tasks/?skip=0&limit=10'
curl -I 'http://localhost:8000/v1/requested-tasks/'
```

This is OK:
```
curl -I 'http://localhost:8000/' =>  200 OK
curl -I 'http://localhost:8000/v1' => 302 FOUND
curl -I 'http://localhost:8000/v1/requested-tasks' => 308 PERMANENT REDIRECT
```

**Comment by rgaudin** [comment]
Removed the bug label. HEAD is not implemented and not mandatory.

**Comment by kelson42** [comment]
> Removed the bug label. HEAD is not implemented and not mandatory.

Then it shoukd return https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501, and this shoukd not trigger an error in Grafana.

**Comment by rgaudin** [comment]
No, it should be `405` as explained in your link. The problem is not much the return code but the fact that it probably crashes the request (we never explicitly set 500 ; the middleware sets it on exceptions).
