### ISSUE TITLE
Add fon

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#842]
New language released from the incubator: fon (same `iso` code). I'll open a separate request for the wiki at [/zim-requests](../../zim-requests/issues)

**Comment by benoit74** [comment]
We do not have to add a language, the UI is listing all languages currently used by at least one Recipe. 
So as mentioned in the UI, we just have to create one Recipe with the new language via the API and job is done. 
I close this task because nothing has to be done on zimfarm codebase / application
I'm at your disposal to create the first Fon recipe with you if you are not confortable to use the API directly.

**Comment by kelson42** [comment]
@benoit74 Is that clearly documented? If not this has to be documented clearly in the FAQ.

**Comment by kelson42** [comment]
> @benoit74 Is that clearly documented? If not this has to be documented clearly in the FAQ. Not the first time this happens. Last time was in June AFAIK.

**Comment by rgaudin** [comment]
That's not the process. @Popolechien has to create the recipe with another language (disabled) and request that a dev changes the language in the DB.

It's been a while since last time and @Popolechien dos it in the wrong order.

Popo please share your recipe link here with language code and name

**Comment by benoit74** [comment]
> @benoit74 Is that clearly documented? If not this has to be documented clearly in the FAQ. Not the first time this happens. Last time was in June AFAIK.

From my PoV, this should be part of a FAQ managed by the content team. We could have a small documentation explaining the part under our responsibility, but most of the work is not done by dev team. Is it ok for you?

**Comment by Popolechien** [comment]
My bad. Pinging @RavanJAltaie since I'm shamelessly dumping this on her.

**Comment by kelson42** [comment]
> > @benoit74 Is that clearly documented? If not this has to be documented clearly in the FAQ. Not the first time this happens. Last time was in June AFAIK.
> 
> 
> 
> From my PoV, this should be part of a FAQ managed by the content team. We could have a small documentation explaining the part under our responsibility, but most of the work is not done by dev team. Is it ok for you?

This is the role of the dev team to document how to use the tool they develop. Here there zero chance that anybody but the devs know what to do to add a language.

Content team is in charge of documenting their own duties, processes and ways to use the tools.

**Comment by benoit74** [comment]
I created the [Add a new language](https://github.com/openzim/zimfarm/wiki/Add-a-new-language).

Is this correct?

What are we supposed to do with ISO 639-3 languages, like 'fon'? Use their ISO 639-1 macrolanguage instead? [Naming Convention](https://github.com/openzim/overview/wiki/Naming-Convention) states clearly that ISO 639-1 must be used.

**Comment by Popolechien** [comment]
Looks good to me.

As for naming, if there's no ISO 639-1 available then we should fall to the next best thing (ie 639-3), it's not like we have many alternatives, do we?

**Comment by benoit74** [comment]
Is really ISO 639-3 supported almost everywhere?

**Comment by rgaudin** [comment]
639-3 is what we use in ZIM metadata

**Comment by RavanJAltaie** [comment]
I've added the recipe in the issue of Zimrequests

**Comment by benoit74** [comment]
Superseeded by #846
