### ISSUE TITLE
Most recipes on farm.openzim.org have stars in secret values

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#849]
See optimization cache URL of https://farm.openzim.org/recipes/ifixit_de_maxi for instance

**Comment by benoit74** [comment]
What we know so far:
- out of 1695 recipes in production, 1382 have `******` in their configuration
- only secret flags are impacted ("api-key", "optimisationCacheUrl", "optimization-cache", "password")
- in the backup from 19th Oct. at 10:05am, there are 5 schedules (out of 1695) with `******` in their configuration
- in the backup from 20th Oct. at 10:05am, there are 1382 schedules (out of 1695) with `******` in their configuration
- this is hence a massive all-at-once change
- the backend has not been redeployed at all in the period (last deploy is from few weeks back)
- we found no code path in the UI / API which could lead to this change, and it makes no sense to modify so many recipes but not all of them, so we are quite sure this something which happened in the background
- we manually fixed the flags of https://farm.openzim.org/pipeline/7b118f70-abf9-4adc-87d3-2cdc36f03359 and requested it manually and it worked well

The scheduling is now disabled (recipes can be requested, but no recipe can be started by the workers).

We are working on data recovery from the backup and will complete this probably tomorrow.

**Comment by rgaudin** [comment]
> this is hence a massive all-at-once change

Within 24h, we have no evidence of it being done in a single _operation_. Can you check if we've had Tasks for all of those with events during that interval?

**Comment by benoit74** [comment]
> Within 24h, we have no evidence of it being done in a single _operation_. Can you check if we've had Tasks for all of those with events during that interval?

Good point, I will check.

**Comment by benoit74** [comment]
Only 7 tasks have an `updated_at` between the 19th and the 20th of October; 16 between the 20th and 21th of October; 106 between the 19th and now.

While we know that `updated_at` is not always updated correctly for every modification which might happen on a task, this is a probable evidence that this change is no linked with a task.

**Comment by benoit74** [comment]
Data modification has been done due to a bug in the "/schedules/backup" endpoint when requested by a user without sufficient privilegies. In such a case, the endpoint replace secrets by `*******`. Unfortunately, a bug was indeed persisting this change into the database instead of just modifying the response.

Endpoint is rarely used, even more by an unauthenticated user. This happened at 17:00 UTC on 19th of Oct.

Bug is not really in our code but more in the cooperation between our code and SQLAlchemy and marshmallow and marshmallow-sqlalchemy.

Bug has been fixed with a "quick-fix" by https://github.com/openzim/zimfarm/commit/def66355587c485a87c2559c842047a41622d8fd

More issues will be open to:
- really identify and fix the root cause (here we have just made a quick fix on a precise case, but the bug could arise somewhere else in the code, we need to understand and fix this)
- implement mitigations to allow escaping the root cause (do not allow DB modifications in operations which are expected to be read-only, force the programmer to specify of DB modifications are expected, ...)

Data has been fixed "manually" (with hand-crafted tools / scripts) in the database, by restoring values modified by the bug with values extracted from a backup.

This incident is hence closed and Zimfarm is progressively recovering normal operation.

**Comment by kelson42** [comment]
@benoit74 A few years ago, working on a sensitive app, we had made to DB handlers: one RW and one RO. We were then usibg the RO DB handler if only read access was needed.

**Comment by benoit74** [comment]
I re-requested 45 recipes which have failed due to our bug (119 have been impacted but 74 have failed many times in a row so useless to relaunch them)

```
finiki
ifixit_de_maxi
klexikon
metakgp
proofwiki
wikibooks_it
wikibooks_pt
wikinews_bg
wikinews_en
wikinews_fa
wikinews_ru
wikipedia_als_all
wikipedia_cu_all
wikipedia_diq_all
wikipedia_el_top
wikipedia_eml_all
wikipedia_fiu-vro_all
wikipedia_ga_all
wikipedia_nap_all
wikipedia_nrm_all
wikipedia_nv_all
wikipedia_pfl_all
wikipedia_pih_all
wikipedia_pl_all
wikipedia_pt_all_app
wikipedia_war_all
wikiquote_en
wikisource_be
wikisource_ca
wikisource_cs
wikisource_da
wikisource_de
wikisource_el
wikisource_he
wikisource_hy
wikisource_it
wikispecies_en_all
wikitech
wikiversity_cs
wikiversity_it
wikivoyage_de
wikivoyage_en_europe_app
wikivoyage_ja
wiktionary_cs
wiktionary_id
```
