### ISSUE TITLE
canadian_prepper task failed suddenly with exit code 247

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#872]
The last [canadian_prepper](https://farm.openzim.org/pipeline/08fea695-635d-4ba7-816d-06d7eb5e0da2/debug) task failed suddenly with a 247 exit code and no message in the logs about this error, as if the error did not really came from the process itself.

This is a youtube recipe, with 277 videos, and the failure happened while building the ZIM file.

Looking on the Internet, it looks like the 247 exit code might come directly from Docker and be linked to a memory issue. It is however real not clear to me if the issue is that the host ran out of memory (but we are supposed to be able to use virt memory) or if Docker decided the container used too much memory (but we do not have any limit in a Docker setup).

@rgaudin Is this something we already encountered (I failed to find Github issues about this)? Do we have any guidance/typical way of work to proceed in such situations?

@RavanJAltaie @Popolechien FYI

**Comment by rgaudin** [comment]
No. Docker adds 128 to its exit code when terminating a container so that would be 119. Very different from regular docker-initiated OOM-related termination.

**Comment by benoit74** [comment]
OK thanks.

**Comment by benoit74** [comment]
ZIM succeeded to be produced on second task mentioned above. I close the PR for now and we will see if the error happens again on same recipe or another one.
