### ISSUE TITLE
Propose systematically a link to the scraper manual/faq in the recipe view

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#889]
Somewhere in the recipe configuration, probably at the location in the screenshot below, we should have a link to the scraper manual / FAQ so that it is easier to find.

![image](https://github.com/openzim/zimfarm/assets/7102089/00a85d31-000e-45dd-94ab-eca6e82a8b48)

**Comment by kelson42** [comment]
@benoit74 Agree!
