### ISSUE TITLE
In the recipe meta form, propose a link to corresponding documentation

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#890]
Somewhere in the recipe configuration, probably at the location in the screenshot below, we should have a link to a generic documentation about all these parameters.

![image](https://github.com/openzim/zimfarm/assets/7102089/371820b4-b78d-4248-901d-3910dd0220d2)

**Comment by kelson42** [comment]
After dicussion, the idea is:
* Create three clear section on the tab (a bit like the scraper command line section)
* Put the help always at the right on the section title, see #889
