### ISSUE TITLE
Issue around zimit lang parameters (confusion between `--lang` and `--zim-lang`)

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#894]
Both [Bouquineux](https://library.kiwix.org/raw/bouquineux.com_fr_all/meta/Language)' and [Saint Libere](https://library.kiwix.org/raw/liberius.net_fr_all/meta/Language)'s meta data are listed as English, yet both recipes have French set up [1](https://farm.openzim.org/recipes/saint_libere/edit), [2](https://farm.openzim.org/recipes/bouquineux/edit)

**Comment by Popolechien** [comment]
I see this issue has been closed by I can't see what the fix is / has been (the zim files mentioned earlier are still assigned to the wrong language, and I have since found others, e.g. https://farm.openzim.org/recipes/slam-out-loud_hi)

**Comment by kelson42** [comment]
@Popolechien Issue is still open

**Comment by Popolechien** [comment]
Ah yes my bad, I saw "transferred" and went off the rails...

**Comment by benoit74** [comment]
Oups, forgot to solve this and then reopened https://github.com/openzim/zimit/issues/315 ... let's do this now.
