### ISSUE TITLE
Set default Publisher to `openZIM` in all offliners

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#900]
As requested in https://github.com/openzim/zim-requests/issues/779, we must harmonize the default Publisher for all our ZIMs.

**Comment by benoit74** [comment]
We have an issue for gutenberg which does not support to set the Publisher on the CLI. We will have to release this scraper first/soon.

@rgaudin : I had a look at the codebase and it is still not clear how you intended to force a default publisher on all offliners at Zimfarm level without having to update all recipes manually. If we do not update the recipe, the configuration is not changed. Did you intended to force this when reading the schedule config to request a task for it? Could you develop a bit what you had in mind?

**Comment by rgaudin** [comment]
It may not be a good solution but I though that we could add it to the command when we compute it (in common/offliners.py I think).

**Comment by benoit74** [comment]
We are mostly on the same page then, I will search what is the "best" solution.

I wonder if this shouldn't be an "official" Zimfarm feature anyway, because anyone using the Zimfarm would probably like to customize the `Publisher` of all the ZIM they will produce and would probably like to not have to do it by hand on all recipes.
