### ISSUE TITLE
Track popular requests

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#912]
This was a soft requirement from the sponsor of the zimit 2.0 update: but we should be able to identify recurring requests over a given period of time.

**Comment by benoit74** [comment]
What has been discussed is a monthly CSV export of tasks from last month ; probably running in Github CI (of kiwix/operations ?), based on a (Python) script and publishing Github CI artifacts.

**Comment by Popolechien** [comment]
LGTM. What are Github artifacts?

**Comment by rgaudin** [comment]
In CI/CD runs, you can upload files directly on Github, it auto expires.
See the bottom of [this one](https://github.com/openzim/python-libzim/actions/runs/10772198785) for an example.

**Comment by benoit74** [comment]
I consider that artifacts are in fact going to be painful, it is hard to see all artifacts from a given CI, so it is not like we can send it easily to our client.

Shall we simply publish it to https://download.openzim.org/ ? And run it in our k8s cluster ? (it is a monthly job, and it is not like we expect it to take lot of resources)

**Comment by benoit74** [comment]
@kelson42 @Popolechien I now need your input on this issue:
- where do we publish these stats files from farm.zimit.kiwix.org? (Github artifacts is not OK for end-users from my PoV)
- should we also publish the ones from farm.openzim.org?
- how should we name each file (`farm.zimit.kiwix.org_2024-08.csv` is OK?)

We should probably discuss it live for simplicity.

**Comment by kelson42** [comment]
> * where do we publish these stats files from farm.zimit.kiwix.org? (Github artifacts is not OK for end-users from my PoV)

I would put them in the drive

> * should we also publish the ones from farm.openzim.org?

Not yet
 
> * how should we name each file (`farm.zimit.kiwix.org_2024-08.csv` is OK?)

`farm.zimit.kiwix.org_tasks_2024-08.csv`

**Comment by benoit74** [comment]
Deployment completed, first report ready, next ones will be automatically populated on 1st days of the month.

https://drive.zimit.kiwix.org/reports/
https://drive.zimit.kiwix.org/reports/farm.zimit.kiwix.org_tasks_2024-08.csv

**Comment by Popolechien** [comment]
For the record (and because I don't know where I'll put this yet I have created a pivot table based off this first .csv that can tell us: 
- how many times a given domain name has been requested
- how these requests occured over the month (so as to quickly see if the same site was requested 10 times in a row; I would use this as a proxy for multiple requests from the same user)

https://docs.google.com/spreadsheets/d/15X_fzE-uvW6x2jM8kokuBosVvP_tRHYpcL4T1Sw-9so/edit?usp=sharing

**Comment by Popolechien** [comment]
@benoit74 Quick follow up question: will there be a way to know whether the requests came from someone with an English or Farsi frontend?

**Comment by benoit74** [comment]
This is possible, not straightforward however (currently we use the public API, not authenticated, so we do not have this information which is considered sensitive, at least it is "hidden" in a sensitive information), so I would prefer to wait to be sure these report are what is needed + we really need this information / it provides meaning. But definitely possible within about 2h work .
