### ISSUE TITLE
Zimfarm not uploading updates

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimfarm#914]
Looking at https://farm.openzim.org/recipes/bccampus_opentextbooks_en_all I see that the recipe has been running quarterly without a hitch yet the last available file was from three runs ago (August, when there were runs in October and January).

Note: recipe has been suspended and warehouse path reset to .hidden/dev as at about the same time it started returning empty files.

**Comment by rgaudin** [comment]
> Note: recipe has been suspended and warehouse path reset to .hidden/dev as at about the same time it started returning empty files.

So what is the issue then?

**Comment by Popolechien** [comment]
No, I mean that I have suspended the recipe and moved the warehouse path, but that's independent of the bug (I did it afterwards but felt necessary to mention it in case you should think it was a setup issue).

The issue is that while it is/was running, new zim files are not uploaded to the library

**Comment by rgaudin** [comment]
- recipe name is incorrect (or `Name`)
- August run created ZIM (now gone but was there)
- October run created ZIM in `dev/`, still there

If the ticket is about the missing August file, see https://github.com/openzim/zim-requests/issues/812

**Comment by rgaudin** [comment]
We only keep 2 versions of a ZIM at the same time. So whem 2023-08 was uploaded, only 2023-05 and 2023-08 were present. When we deleted 2023-08, only one is left… until a second one arrives

**Comment by rgaudin** [comment]
October one is [here](https://mirror.download.kiwix.org/zim/.hidden/dev/opentextbooks_en_all_2023-10.zim)

**Comment by rgaudin** [comment]
It's in dev ; now are you talking about the Library? That's different from a ZIM file and there can be an issue preventing it from entering the library

**Comment by Popolechien** [comment]
ok I was CTRL + F for bcccampus.

Looks like a giant mixup, but since the last run uploaded properly to /dev I suppose that my initial point is moot. Closing for now. thanks.

**Comment by rgaudin** [comment]
> ok I was CTRL + F for bcccampus.

Exactly ; recipe and Name are different. This needs to be fixed
