### ISSUE TITLE
Config not displayed properly in not logged-in

### ISSUE THREAD

**Issue by kelson42** [openzim/zimfarm#936]
See for example:
![grafik](https://github.com/openzim/zimfarm/assets/1029718/f4f50d82-8df3-4a40-b66b-0becfa927940)

I see only each parameter name, but not the value.

I should be able to see the full configuration

**Comment by rgaudin** [comment]
Pretty sure it's a duplicate. That's the horizontal scroll in action. Looks like a recent? change made the command part of the overall column

**Comment by jairajmahadev** [comment]
@kelson42 can you send the link where you are experiencing this bug? I'm trying to see if I can fix this. I tried visiting the page but could not recreate the bug.
![image](https://github.com/openzim/zimfarm/assets/79752773/dd34f9c2-2ade-4185-820c-79d23595a4ca)

**Comment by benoit74** [comment]
@jairajmahadev You have to go to a specific task and to the debug tab: e.g. https://farm.openzim.org/pipeline/495d8bfd-928d-4bad-96e1-a99b0364a259/debug

**Comment by jairajmahadev** [comment]
@benoit74 adding ```style="word-wrap: break-word;min-width: 160px;max-width: 160px; white-space: normal;"``` to the ```<td>``` tag fixed the problem. Is this correct?

**Comment by poju3185** [comment]
I fixed it by adding `max-width` constrain to the `stdout` class.

**Comment by benoit74** [comment]
@jairajmahadev propose a PR with all details (or even better, explain why @poju3185 PR is not sufficient to fix the issue)

**Comment by jairajmahadev** [comment]
@benoit74 @poju3185 's PR assumes only stdout and stderr to be very large. In reality, any of the table rows could contain a large string, which could, in the future, again cause a very long horizontal scroll and hide the config parameter values. Also just adding a constraint to the width would cause the height to increase, which would again make the table unreadable.

**Comment by poju3185** [comment]
Hi @jairajmahadev, thank you for your contributions in the PR.
I'd like to point out that In your PR you also assume that only stdout and command to be large. Furthermore,the command class already implements `word-wrap: anywhere;`, which manages its length without necessitating truncation. Also adding a constraint to the width will not cause the height to increase because it is designed to be scrollable.

**Comment by jairajmahadev** [comment]
@poju3185 thanks for your feedback
