### ISSUE TITLE
Task scheduling should also take into account requested task "age"

### ISSUE THREAD

**Issue by benoit74** [openzim/zimfarm#946]
For now, when deciding which is the next task a worker should start, the scheduling algorithm order requested task first by priority, then by expected duration.

It would be great to also take into account the requested task "age" (i.e. duration since requested date), so that tasks requested a long time ago are started first. This is especially important for the situation (like youzim.it) where all tasks have the same priority and expected/empty duration.

I suggest to simply add the age as a third sorting criteria.

Another alternative would be to create a weighted approach between priority, expected duration and age, but it seems a daunting task (weigths would be difficult to decide) for a limited added value.

**Comment by rgaudin** [comment]
Adding a third criteria should do the job
